"""Parse and apply the critic's edit directives over a merged proposal.

The critic used to be handed a proposal and asked for the proposal back. That
regenerates 55 KB to change 400 bytes of it — measured at 173–630 s a pass, for
edits under 1% of the document — and every one of those regenerated bytes is a
chance to silently reword a ``**Source:**`` line the reviewer trusts.

So the critic now emits *directives* and this module applies them, in code:

    REPLACE <file>#<n> <text>          swap an entry's proposed text
    MOVE <file>#<n> -> <other.md>      re-target a misrouted entry
    TO-ACTION <file>#<n>               it is a toolchain change, not a memory
    DROP <file>#<n> <reason>           filter it out
    MERGE <file>#<n> <- <file>#<m>     fold m into n, keeping BOTH Source lines
    NOOP                               nothing to change

Two rules make this safe to run unattended.

**Provenance is not editable.** A directive that would alter or delete a
``**Source:**`` line is refused, not best-efforted. The single sanctioned
exception is ``MERGE``, which *appends* — the surviving entry ends up carrying
both citations verbatim. ``DROP`` removes an entry's Source with the entry,
which is the point of dropping it.

**Nothing raises.** A critic is a model; its output is arbitrary text. Garbage
parses to zero directives and applies as a no-op returning the input document
byte-identical, so a bad second pass costs a log line and never a proposal.

Entry ranges are resolved once against the *input* document and then applied
back-to-front, so an index in one directive can never be shifted by another
directive's edit — the failure mode where ``DROP dev.md#2`` silently makes
``DROP dev.md#5`` hit the wrong entry.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Sequence

logger = logging.getLogger(__name__)

OPS = ("REPLACE", "MOVE", "TO-ACTION", "DROP", "MERGE", "NOOP")

_UPDATES_FOR_RE = re.compile(r"^## Updates for `(?P<file>[^`]+)`")
_ACTIONS_RE = re.compile(r"^## Action Items\b")
_FILTERED_RE = re.compile(r"^## Filtered Out\b")
_ENTRY_RE = re.compile(r"^### (?P<num>\d+)\.(?P<rest>.*)$")
_ACTION_ENTRY_RE = re.compile(r"^### A(?P<num>\d+)\.(?P<rest>.*)$")
# Mirrors lib/dream_processed.py: an entry block ends at the next heading or rule.
_BLOCK_BOUNDARY_RE = re.compile(r"^(?:#{2,3}\s|-{3,}\s*$)")
_RULE_ONLY_RE = re.compile(r"^-{3,}\s*$")
_SOURCE_PREFIX = "**Source:**"

_REF_RE = r"(?P<file>[^\s#]+)#(?P<index>\d+)"
_REPLACE_RE = re.compile(rf"^REPLACE\s+{_REF_RE}\s+(?P<arg>.+)$")
_MOVE_RE = re.compile(rf"^MOVE\s+{_REF_RE}\s*->\s*(?P<arg>\S+)\s*$")
_TO_ACTION_RE = re.compile(rf"^TO-ACTION\s+{_REF_RE}\s*(?P<arg>.*)$")
_DROP_RE = re.compile(rf"^DROP\s+{_REF_RE}\s*(?P<arg>.*)$")
_MERGE_RE = re.compile(
    r"^MERGE\s+(?P<file>[^\s#]+)#(?P<index>\d+)\s*<-\s*"
    r"(?P<src_file>[^\s#]+)#(?P<src_index>\d+)\s*$"
)
_NOOP_RE = re.compile(r"^NOOP\b.*$")

_ACTIONS_HEADING = "## Action Items"


@dataclass(frozen=True)
class Directive:
    """One critic edit, already resolved to (op, target file, entry index)."""

    op: str
    target_file: str
    index: int
    arg: str | None = None
    src_file: str | None = None
    src_index: int | None = None


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_directives(text: str) -> tuple[list[Directive], list[str]]:
    """Parse the critic's response into directives and the lines that failed.

    Blank lines and markdown code fences are ignored rather than rejected —
    models wrap line-oriented output in ``` about half the time, and counting
    that as three rejections would make the "how noisy was the critic?" number
    meaningless. Everything else that does not parse is returned verbatim so
    the caller can log exactly what it refused to act on.
    """
    parsed: list[Directive] = []
    rejected: list[str] = []
    for raw in (text or "").splitlines():
        line = raw.strip()
        if not line or line.startswith("```"):
            continue
        directive = _parse_line(line)
        if directive is None:
            rejected.append(raw)
        elif directive.op != "NOOP":
            parsed.append(directive)
    return parsed, rejected


def _parse_line(line: str) -> Directive | None:
    if _NOOP_RE.match(line):
        return Directive(op="NOOP", target_file="", index=0)
    m = _MERGE_RE.match(line)
    if m:
        return Directive(
            op="MERGE",
            target_file=m.group("file"),
            index=int(m.group("index")),
            src_file=m.group("src_file"),
            src_index=int(m.group("src_index")),
        )
    m = _MOVE_RE.match(line)
    if m:
        return Directive("MOVE", m.group("file"), int(m.group("index")), m.group("arg"))
    m = _REPLACE_RE.match(line)
    if m:
        return Directive(
            "REPLACE", m.group("file"), int(m.group("index")), m.group("arg").strip()
        )
    m = _TO_ACTION_RE.match(line)
    if m:
        # TO-ACTION is retired: there is no Action Items section to move an entry
        # into any more. It is still *parsed* because the critic is a model, not a
        # parser — it emitted this shape for months and a stray one must not create
        # a section the reviewer is told cannot exist. Its meaning ("this is a
        # toolchain change-request, not memory") is exactly DROP's, so it becomes
        # one, carrying the reason the Filtered Out section needs.
        return Directive(
            "DROP", m.group("file"), int(m.group("index")),
            m.group("arg").strip() or "toolchain change-request",
        )
    m = _DROP_RE.match(line)
    if m:
        return Directive(
            "DROP", m.group("file"), int(m.group("index")), m.group("arg").strip() or None
        )
    return None


# ---------------------------------------------------------------------------
# Document model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class _Section:
    kind: str        # "update" | "action" | "other"
    name: str        # target file for "update", "" otherwise
    head: int        # index of the heading line
    end: int         # exclusive end of the section


def _sections(lines: Sequence[str]) -> list[_Section]:
    heads = [i for i, line in enumerate(lines) if line.startswith("## ")]
    out: list[_Section] = []
    bounds = heads + [len(lines)]
    for head, end in zip(bounds, bounds[1:]):
        line = lines[head]
        m = _UPDATES_FOR_RE.match(line)
        if m:
            out.append(_Section("update", m.group("file"), head, end))
        elif _ACTIONS_RE.match(line):
            out.append(_Section("action", "", head, end))
        else:
            out.append(_Section("other", "", head, end))
    return out


def _entry_ranges(lines: Sequence[str]) -> dict[tuple[str, str, int], tuple[int, int]]:
    """Map every entry to its ``[start, end)`` line range in *lines*.

    Keys are ``("update", target_file, n)`` and ``("action", "", n)`` — the same
    ``(kind, target, index)`` triple ``lib/dream_processed.py`` and the GUI hub
    resolve a decision against, so a directive and a decision cannot disagree
    about which entry ``dev.md#3`` is.
    """
    ranges: dict[tuple[str, str, int], tuple[int, int]] = {}
    for section in _sections(lines):
        if section.kind == "other":
            continue
        pattern = _ENTRY_RE if section.kind == "update" else _ACTION_ENTRY_RE
        for i in range(section.head + 1, section.end):
            m = pattern.match(lines[i])
            if not m:
                continue
            end = section.end
            for j in range(i + 1, section.end):
                if _BLOCK_BOUNDARY_RE.match(lines[j]):
                    end = j
                    break
            while end > i + 1 and not lines[end - 1].strip():
                end -= 1
            key = (section.kind, section.name, int(m.group("num")))
            ranges.setdefault(key, (i, end))
    return ranges


def _sources(block: Sequence[str]) -> list[str]:
    return [line for line in block if line.lstrip().startswith(_SOURCE_PREFIX)]


def _title(block: Sequence[str]) -> str:
    m = _ENTRY_RE.match(block[0]) or _ACTION_ENTRY_RE.match(block[0])
    return (m.group("rest").strip() if m else block[0].lstrip("# ")).strip()


def _renumber(block: list[str], number: int, prefix: str = "") -> list[str]:
    """Rewrite only the ``### N.`` heading line; the rest is copied verbatim."""
    pattern = _ACTION_ENTRY_RE if prefix else _ENTRY_RE
    m = pattern.match(block[0])
    rest = m.group("rest") if m else ""
    return [f"### {prefix}{number}.{rest}", *block[1:]]


# ---------------------------------------------------------------------------
# Applying
# ---------------------------------------------------------------------------

def apply_directives(
    proposal: str, directives: Sequence[Directive]
) -> tuple[str, list[str], list[str]]:
    """Apply *directives* to *proposal*.

    Returns ``(new_proposal, applied, refused)``. ``applied`` and ``refused``
    are human-readable lines for the log. Fail-open: any internal error returns
    the untouched proposal with the error as a single refusal, because a critic
    pass that cannot run must still leave a usable document behind.
    """
    try:
        return _apply(proposal, directives)
    except Exception as exc:  # pragma: no cover - defensive, must never raise
        logger.exception("Directive application failed — keeping the merged draft")
        return proposal, [], [f"internal error, no directives applied: {exc}"]


def _apply(
    proposal: str, directives: Sequence[Directive]
) -> tuple[str, list[str], list[str]]:
    lines = proposal.splitlines()
    ranges = _entry_ranges(lines)

    applied: list[str] = []
    refused: list[str] = []
    edits: list[tuple[int, int, list[str]]] = []
    claimed: set[tuple[str, str, int]] = set()
    pending_moves: dict[str, list[list[str]]] = {}
    pending_actions: list[list[str]] = []
    pending_filtered: list[str] = []

    # Descending index within each file: the ranges above are already frozen
    # against the input, so this is belt-and-braces — but it also makes the
    # result independent of the order the critic happened to emit directives in.
    ordered = sorted(directives, key=lambda d: (d.target_file, -d.index))

    for d in ordered:
        ref = f"{d.target_file}#{d.index}"
        key = _resolve(d.target_file, d.index, ranges)
        if key is None:
            refused.append(f"{d.op} {ref}: no such entry")
            continue
        if key in claimed:
            refused.append(f"{d.op} {ref}: entry already edited by an earlier directive")
            continue
        block = lines[slice(*ranges[key])]

        if d.op == "REPLACE":
            new_block, reason = _replace_block(block, d.arg or "")
            if new_block is None:
                refused.append(f"REPLACE {ref}: {reason}")
                continue
            edits.append((*ranges[key], new_block))
            applied.append(f"REPLACE {ref}")

        elif d.op == "DROP":
            edits.append((*ranges[key], []))
            pending_filtered.append(_filtered_line(block, d.arg))
            applied.append(f"DROP {ref}" + (f" ({d.arg})" if d.arg else ""))

        elif d.op == "MOVE":
            dest = (d.arg or "").strip()
            if not dest or dest == d.target_file:
                refused.append(f"MOVE {ref}: destination missing or unchanged")
                continue
            if key[0] != "update":
                refused.append(f"MOVE {ref}: only memory entries can be re-targeted")
                continue
            edits.append((*ranges[key], []))
            pending_moves.setdefault(dest, []).append(list(block))
            applied.append(f"MOVE {ref} -> {dest}")

        elif d.op == "TO-ACTION":
            if key[0] != "update":
                refused.append(f"TO-ACTION {ref}: already an action item")
                continue
            action = _to_action(block, d.target_file, d.arg)
            if not _sources(action) and _sources(block):
                refused.append(f"TO-ACTION {ref}: would drop the **Source:** line")
                continue
            edits.append((*ranges[key], []))
            pending_actions.append(action)
            applied.append(f"TO-ACTION {ref}")

        elif d.op == "MERGE":
            src_key = _resolve(d.src_file or "", d.src_index or 0, ranges)
            src_ref = f"{d.src_file}#{d.src_index}"
            if src_key is None:
                refused.append(f"MERGE {ref} <- {src_ref}: no such entry")
                continue
            if src_key == key:
                refused.append(f"MERGE {ref} <- {src_ref}: cannot merge an entry into itself")
                continue
            if src_key in claimed:
                refused.append(
                    f"MERGE {ref} <- {src_ref}: entry already edited by an earlier directive"
                )
                continue
            src_block = lines[slice(*ranges[src_key])]
            carried = _sources(src_block)
            if not carried:
                refused.append(
                    f"MERGE {ref} <- {src_ref}: absorbed entry has no **Source:** line to carry"
                )
                continue
            merged = _append_sources(block, carried)
            if merged is None:
                refused.append(f"MERGE {ref} <- {src_ref}: surviving entry has no **Source:** line")
                continue
            edits.append((*ranges[key], merged))
            edits.append((*ranges[src_key], []))
            claimed.add(src_key)
            applied.append(f"MERGE {ref} <- {src_ref}")

        else:  # pragma: no cover - parse_directives never emits another op
            refused.append(f"{d.op} {ref}: unknown operation")
            continue

        claimed.add(key)

    if not edits and not pending_moves and not pending_actions:
        return proposal, applied, refused

    for start, end, replacement in sorted(edits, key=lambda e: -e[0]):
        lines[start:end] = replacement

    for dest in sorted(pending_moves):
        for block in pending_moves[dest]:
            lines = _append_to_update_section(lines, dest, block)
    for block in pending_actions:
        lines = _append_to_actions(lines, block)
    for line in pending_filtered:
        lines = _append_to_filtered(lines, line)

    lines = _refresh_counts(_renumber_all(lines))
    return _tidy(lines), applied, refused


def _resolve(file_name: str, index: int, ranges: dict) -> tuple[str, str, int] | None:
    """Resolve a ``<file>#<n>`` reference to an entry key.

    ``Action Items`` has no filename, so the critic refers to it by the section
    name; accept the obvious spellings rather than refusing a directive that is
    unambiguous to a human.
    """
    if ("update", file_name, index) in ranges:
        return ("update", file_name, index)
    if file_name.lower().replace("_", "-") in ("action-items", "actions", "action"):
        if ("action", "", index) in ranges:
            return ("action", "", index)
    if ("action", "", index) in ranges and file_name == "":
        return ("action", "", index)
    return None


def _replace_block(block: list[str], text: str) -> tuple[list[str] | None, str]:
    """Swap an entry's proposed insert text, keeping every other line as-is.

    Only the ``> `` blockquote run is rewritten, so ``**Section:**``,
    ``**Change:**`` and ``**Source:**`` survive by construction. A replacement
    that itself contains a Source line is refused outright — that is the shape
    of a critic trying to rewrite provenance.
    """
    if not text:
        return None, "empty replacement text"
    if _SOURCE_PREFIX in text:
        return None, "replacement text would rewrite the **Source:** line"
    quotes = [i for i, line in enumerate(block) if line.lstrip().startswith(">")]
    if not quotes:
        return None, "entry has no quoted text to replace"
    new = [*block[:quotes[0]], f"> {text}", *block[quotes[-1] + 1:]]
    if _sources(new) != _sources(block):
        return None, "would alter the **Source:** line"
    return new, ""


def _append_sources(block: list[str], carried: list[str]) -> list[str] | None:
    """Append absorbed Source lines directly after the entry's own last one.

    The one sanctioned provenance edit in this module: both citations end up in
    the surviving entry verbatim, so a merged pair remains traceable to both
    learnings records.
    """
    positions = [i for i, line in enumerate(block) if line.lstrip().startswith(_SOURCE_PREFIX)]
    if not positions:
        return None
    at = positions[-1] + 1
    return [*block[:at], *carried, *block[at:]]


def _to_action(block: list[str], origin: str, reason: str | None) -> list[str]:
    """Reformat a memory entry as an ``### A{N}.`` action item, verbatim Source.

    The placeholder number is fixed up by the renumbering pass, so this function
    never has to know how many action items already exist.
    """
    quoted = [
        line.lstrip()[1:].strip()
        for line in block
        if line.lstrip().startswith(">")
    ]
    what = " ".join(q for q in quoted if q) or _title(block)
    why = reason or f"Filed under `{origin}` but it is a change to the toolchain, not a memory."
    return [
        f"### A0. {_title(block)}",
        f"**What:** {what}",
        f"**Why:** {why}",
        *_sources(block),
    ]


# ---------------------------------------------------------------------------
# Insertion + renumbering
# ---------------------------------------------------------------------------

def _back(lines: list[str], idx: int, floor: int = 0) -> int:
    """Walk *idx* back over the blank/``---`` run that separates two sections.

    Insertions land at the returned index, i.e. after the last real content and
    *before* the separator — appending after the rule instead is how an entry
    ends up visually filed under the following section.
    """
    while idx > floor and (not lines[idx - 1].strip() or _RULE_ONLY_RE.match(lines[idx - 1])):
        idx -= 1
    return idx


def _new_section_point(lines: list[str], sections: list[_Section], kind: str) -> int:
    """Where a brand-new section goes, preserving the canonical section order
    (update groups, then ``## Action Items``, then ``## Filtered Out``)."""
    updates = [s for s in sections if s.kind == "update"]
    if kind == "action":
        for s in sections:
            if _FILTERED_RE.match(lines[s.head]):
                return _back(lines, s.head)
        if updates:
            return _back(lines, updates[-1].end, updates[-1].head + 1)
        return len(lines)
    if updates:
        return _back(lines, updates[-1].end, updates[-1].head + 1)
    for s in sections:
        if s.kind == "action" or _FILTERED_RE.match(lines[s.head]):
            return _back(lines, s.head)
    return len(lines)


def _append_to_update_section(lines: list[str], dest: str, block: list[str]) -> list[str]:
    sections = _sections(lines)
    for s in sections:
        if s.kind == "update" and s.name == dest:
            at = _back(lines, s.end, s.head + 1)
            return [*lines[:at], "", *block, *lines[at:]]
    at = _new_section_point(lines, sections, "update")
    return [*lines[:at], "", "---", "", f"## Updates for `{dest}`", "", *block, *lines[at:]]


def _filtered_line(block: list[str], reason: str | None) -> str:
    """The one-line audit record a DROP leaves behind in ``## Filtered Out``.

    A dropped entry must stay visible: under the ledger its source block is
    marked consolidated and will never resurface, and the standing licence to
    delete a learnings file rests on "the reviewer saw everything that was
    dropped". A DROP that vanished silently would make that false.
    """
    citations = "; ".join(
        s.lstrip()[len(_SOURCE_PREFIX):].strip() for s in _sources(block)
    )
    tail = f" (Source: {citations})" if citations else ""
    return f"- {_title(block)} — {reason or 'dropped by the critic'}{tail}"


def _append_to_filtered(lines: list[str], line: str) -> list[str]:
    sections = _sections(lines)
    for s in sections:
        if _FILTERED_RE.match(lines[s.head]):
            at = _back(lines, s.end, s.head + 1)
            return [*lines[:at], line, *lines[at:]]
    at = len(lines)
    return [*lines[:at], "", "---", "", "## Filtered Out (0 items)", "", line]


def _refresh_counts(lines: list[str]) -> list[str]:
    """Keep the ``(N items)`` in the Action Items / Filtered Out headings honest.

    Cosmetic, but a heading that says "1 items" over three is the kind of
    mismatch that makes a reviewer distrust the whole document.
    """
    out = list(lines)
    for s in _sections(out):
        body = out[s.head + 1:s.end]
        if s.kind == "action":
            n = sum(1 for line in body if _ACTION_ENTRY_RE.match(line))
            out[s.head] = f"{_ACTIONS_HEADING} ({n} items)"
        elif _FILTERED_RE.match(out[s.head]):
            n = sum(1 for line in body if line.lstrip().startswith("- "))
            out[s.head] = f"## Filtered Out ({n} items)"
    return out


def _append_to_actions(lines: list[str], block: list[str]) -> list[str]:
    sections = _sections(lines)
    for s in sections:
        if s.kind == "action":
            at = _back(lines, s.end, s.head + 1)
            return [*lines[:at], "", *block, *lines[at:]]
    at = _new_section_point(lines, sections, "action")
    return [*lines[:at], "", "---", "", _ACTIONS_HEADING, "", *block, *lines[at:]]


def _renumber_all(lines: list[str]) -> list[str]:
    """Renumber updates ``1..N`` across the whole proposal, actions ``A1..Ak``.

    Necessary after any DROP/MOVE/MERGE: the reference the reviewer and the hub
    resolve is ``(kind, target, index)``, and holes in the numbering make two
    entries fight over one index the moment anything else is inserted.

    Updates share ONE counter across every ``## Updates for`` section, matching
    what ``proposal_merge.merge_drafts`` produced before the critic ran. This
    runs after every applied directive, so a per-section counter here would
    silently restore per-file numbering on any proposal the critic touched —
    i.e. on almost all of them. Actions keep their own ``A``-counter; there is
    only ever one Action Items section, so the distinction does not arise.
    """
    out = list(lines)
    update_n = 0
    for section in _sections(out):
        if section.kind == "other":
            continue
        pattern = _ENTRY_RE if section.kind == "update" else _ACTION_ENTRY_RE
        prefix = "" if section.kind == "update" else "A"
        action_n = 0
        for i in range(section.head + 1, section.end):
            m = pattern.match(out[i])
            if m:
                if section.kind == "update":
                    update_n += 1
                    n = update_n
                else:
                    action_n += 1
                    n = action_n
                out[i] = f"### {prefix}{n}.{m.group('rest')}"
    return out


def _tidy(lines: list[str]) -> str:
    """Collapse the blank-line runs an excision leaves behind."""
    out: list[str] = []
    for line in lines:
        if not line.strip() and out and not out[-1].strip():
            continue
        out.append(line)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out) + "\n"
