"""Dream consolidation script for multiplai plugin.

Default mode (no flags): generates a human-readable change proposal and writes it
to .multiplai/dreams/ for review. Run /multiplai-context:dream-remember to apply.

--auto: fully autonomous — applies changes directly to memory files without review.
--check: report pending learnings count and exit.
"""

import asyncio
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from lib.venv_guard import ensure_venv_python
ensure_venv_python()

from lib.paths import get_paths
from lib.model_client import create_client
from lib.config import load_yaml, save_yaml
from lib.log_utils import setup_logging
from generators.config import load_catalog_config
from generators.dispatcher import generate_catalogs

logger = setup_logging("dream")


# ---------------------------------------------------------------------------
# Learnings I/O
# ---------------------------------------------------------------------------

def _read_all_learnings(learnings_dir: Path) -> tuple[str, list[Path]]:
    """Read all pending learnings files. Returns (combined_text, source_files)."""
    if not learnings_dir.exists():
        return "", []
    files = sorted(learnings_dir.glob("*.md"))
    if not files:
        return "", []
    parts = []
    for f in files:
        content = f.read_text().strip()
        if content:
            parts.append(f"### File: {f.name}\n\n{content}")
    combined = "\n\n---\n\n".join(parts)
    return combined, files


def _read_memory_files(memory_dir: Path) -> dict[str, str]:
    """Return {filename: content} for all .md files in memory_dir."""
    if not memory_dir.exists():
        return {}
    return {
        f.name: f.read_text()
        for f in sorted(memory_dir.glob("*.md"))
        if f.name != "learnings.md"
    }


def _extract_headers(content: str) -> str:
    """Return H1–H3 headers from markdown content."""
    headers = [l for l in content.split("\n") if l.startswith("#")]
    return "\n".join(headers) if headers else content[:300]


# ---------------------------------------------------------------------------
# Report mode (default)
# ---------------------------------------------------------------------------

_PROPOSAL_SYSTEM = """\
You are a memory consolidation analyst for a personal Claude Code memory system.

Given accumulated session learnings and the current structure of memory files, produce
a structured PROPOSAL showing what should change in which files. Do NOT rewrite files —
output a human-readable proposal for the user to review and approve.

## Output format

```
# Processed Learnings — {date}

**Sources:** {N} files, ~{M} entries
Generated by Dream. Review with `/multiplai-context:dream-remember` to apply.

---

## Updates for `{filename}` ({N} learnings)

### {N}. [{trust_level}[, seen {Nx}]] {short_title}
**Section:** {existing section or "New section"}
**Change:** add / update / replace
> Exact text to insert or modify (markdown formatted, concise)

**Source:** {filename(s)}

---

## Filtered Out ({N} items)

- "{short description}": {reason} (already present / too specific / low trust / superseded)
```

## Rules

- Group updates by target memory file.
- Deduplicate: if the same lesson appears multiple times, merge into one entry and note the count ("seen 3x"). Repetition elevates priority.
- Resolve contradictions: keep the most recent high-trust version; note what was superseded.
- Trust hierarchy: authoritative > verified/high > unverified/low. Don't propose low-trust single-occurrence items.
- Mark RULE-PROPOSAL items (changes to CLAUDE.md behavioral rules) with **[RULE-PROPOSAL]** in the title — these require individual approval.
- Filter out: already-applied facts, one-time bug fixes that don't reveal a general pattern, entries with no clear target file.
- Keep proposed text concise — one-line bullets over paragraphs. Memory costs tokens.
- Never invent changes not supported by the learnings.
"""


async def _generate_proposal(
    client,
    all_learnings: str,
    memory_contents: dict[str, str],
    source_files: list[Path],
) -> str:
    """Call LLM to produce a structured change proposal from learnings."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    source_names = ", ".join(f.name for f in source_files)

    memory_context = "\n\n".join(
        f"### {name} (structure):\n{_extract_headers(content)}"
        for name, content in memory_contents.items()
    )

    messages = [
        {
            "role": "user",
            "content": (
                f"Today's date: {today}\n"
                f"Source files: {source_names}\n\n"
                f"## Current memory file structure:\n\n{memory_context}\n\n"
                f"## Pending learnings:\n\n{all_learnings}"
            ),
        }
    ]

    response = await client.query(system=_PROPOSAL_SYSTEM, messages=messages)
    return response.content


async def dream_report() -> None:
    """Generate a change proposal and write it to .multiplai/dreams/ for review."""
    paths = get_paths()
    learnings_dir = paths.learnings_dir
    memory_dir = paths.memory_dir()
    dreams_dir = paths.dreams_dir()

    all_learnings, source_files = _read_all_learnings(learnings_dir)
    if not all_learnings:
        print("No pending learnings — nothing to propose.")
        return

    learnings_bytes = len(all_learnings.encode("utf-8"))
    learnings_lines = len(all_learnings.splitlines())
    logger.info(
        "Source learnings: %d files (%d lines, %d bytes): %s",
        len(source_files), learnings_lines, learnings_bytes,
        ", ".join(f.name for f in source_files),
    )

    client = await create_client()
    logger.info("Dream using %s", type(client).__name__)

    memory_contents = _read_memory_files(memory_dir)
    logger.info(
        "Loaded %d memory files for context: %s",
        len(memory_contents), ", ".join(sorted(memory_contents)),
    )

    proposal = await _generate_proposal(client, all_learnings, memory_contents, source_files)

    # Quick structural digest so the log answers "what did the model decide?"
    # without having to open the proposal file.
    proposal_lines = proposal.splitlines()
    target_files = [
        l.split("`")[1] for l in proposal_lines
        if l.startswith("## Updates for `") and "`" in l[15:]
    ]
    has_filtered = any(l.startswith("## Filtered Out") for l in proposal_lines)
    logger.info(
        "Proposal generated: %d bytes, %d target files (%s), filtered-out section=%s",
        len(proposal.encode("utf-8")),
        len(target_files),
        ", ".join(target_files) if target_files else "none",
        has_filtered,
    )
    if not has_filtered or not target_files:
        logger.warning(
            "Proposal looks incomplete — missing target updates or Filtered Out section"
        )

    dreams_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    output_file = dreams_dir / f"processed-learnings-{today}.md"
    output_file.write_text(proposal)
    logger.info("Proposal written to %s", output_file)

    print(f"Proposal written to {output_file}")
    print(f"Sources: {len(source_files)} files, ~{learnings_lines} lines")
    print(f"Targets: {len(target_files)} files ({', '.join(target_files) or 'none'})")
    print("Review with: /multiplai-context:dream-remember")


# ---------------------------------------------------------------------------
# Auto mode (--auto)
# ---------------------------------------------------------------------------

def _memory_dir_is_git_repo(memory_dir: Path) -> bool:
    if not memory_dir.exists():
        return False
    try:
        result = subprocess.run(
            ["git", "-C", str(memory_dir), "rev-parse", "--is-inside-work-tree"],
            capture_output=True, text=True, timeout=10,
        )
        return result.returncode == 0 and result.stdout.strip() == "true"
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return False


def _commit_memory_changes(memory_dir: Path) -> bool:
    """Stage and commit memory changes. Returns True on commit, False otherwise."""
    if not _memory_dir_is_git_repo(memory_dir):
        logger.warning(
            "Memory auto-commit skipped — %s is not a git repository.", memory_dir
        )
        return False

    try:
        # Stage only memory markdown files. Staging the whole tree would
        # sweep in unrelated dirty work when memory_dir lives inside a
        # larger repo (dotfiles/workspace) and record it in the snapshot.
        subprocess.run(
            ["git", "-C", str(memory_dir), "add", "--", "*.md"],
            check=True, timeout=15, capture_output=True,
        )
        diff = subprocess.run(
            ["git", "-C", str(memory_dir), "diff", "--cached", "--quiet"],
            timeout=10, capture_output=True,
        )
        if diff.returncode == 0:
            logger.info("Memory auto-commit skipped — no changes to commit")
            return False

        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        subprocess.run(
            ["git", "-C", str(memory_dir), "commit", "-m", f"dream: consolidate {today}"],
            check=True, timeout=30, capture_output=True,
        )
        logger.info("Memory auto-committed in %s", memory_dir)
        return True
    except subprocess.CalledProcessError as e:
        logger.warning(
            "Memory auto-commit failed: git %s exited %d (stderr: %s)",
            e.cmd, e.returncode, e.stderr.decode("utf-8", "replace") if e.stderr else "",
        )
        return False
    except (subprocess.SubprocessError, FileNotFoundError, OSError) as e:
        logger.warning("Memory auto-commit failed: %s", e)
        return False


async def _update_memory_file(client, memory_file: Path, learnings: str) -> str | None:
    """Use LLM to consolidate learnings directly into a single memory file."""
    if not memory_file.exists():
        return None

    current_content = memory_file.read_text()
    system = (
        "You are a memory consolidation assistant. Given the current memory file "
        "and new learnings, produce an updated version of the memory file that "
        "integrates relevant learnings. Preserve existing structure and content. "
        "Return the full updated file content."
    )
    messages = [
        {
            "role": "user",
            "content": (
                f"## Current memory file ({memory_file.name}):\n{current_content}\n\n"
                f"## New learnings to integrate:\n{learnings}"
            ),
        }
    ]

    try:
        response = await client.query(system=system, messages=messages)
        return response.content
    except Exception:
        logger.exception("Failed to update %s", memory_file.name)
        return None


async def dream_auto() -> None:
    """Apply learnings directly to memory files without review (autonomous mode)."""
    paths = get_paths()
    learnings_dir = paths.learnings_dir
    memory_dir = paths.memory_dir()
    dream_state_file = paths.dream_state_file()

    all_learnings, source_files = _read_all_learnings(learnings_dir)
    if not all_learnings:
        logger.info("No pending learnings to consolidate")
    else:
        try:
            client = await create_client()
            logger.info("Dream (auto) using %s", type(client).__name__)

            memory_files = list(memory_dir.iterdir()) if memory_dir.exists() else []
            memory_files = [f for f in memory_files if f.suffix == ".md" and f.name != "learnings.md"]

            if memory_files:
                tasks = [_update_memory_file(client, mf, all_learnings) for mf in memory_files]
                results = await asyncio.gather(*tasks)

                updated_count = 0
                for memory_file, updated_content in zip(memory_files, results):
                    if updated_content:
                        memory_file.write_text(updated_content)
                        updated_count += 1
                        logger.info("Updated %s", memory_file.name)

                # Delete processed learnings files
                for f in source_files:
                    f.unlink(missing_ok=True)
                    logger.info("Deleted processed learnings: %s", f.name)

                state = load_yaml(dream_state_file)
                state["last_run"] = datetime.now(timezone.utc).isoformat()
                state["learnings_processed"] = sum(1 for _ in all_learnings.splitlines())
                state["files_updated"] = updated_count
                save_yaml(dream_state_file, state)

                logger.info("Dream (auto) complete: %d files updated", updated_count)
            else:
                logger.info("No memory files found to update")
        except Exception:
            logger.exception("Dream (auto) consolidation failed")
            raise

    try:
        config = load_catalog_config()
        catalog_results = await generate_catalogs(config=config)
        logger.info("Catalog regeneration complete: %d generators ran", len(catalog_results))
    except Exception:
        logger.exception("Catalog generation failed (dream still complete)")

    _commit_memory_changes(memory_dir)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Dream — learnings consolidation")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report pending learnings count and exit",
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="Apply changes directly to memory files without review (autonomous mode)",
    )
    # --run kept as deprecated alias for --auto
    parser.add_argument("--run", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args()

    if args.check:
        paths = get_paths()
        _, files = _read_all_learnings(paths.learnings_dir)
        if not files:
            print("No pending learnings")
            return
        total_lines = sum(
            len(f.read_text().splitlines()) for f in files
        )
        print(f"Pending learnings: {len(files)} files, ~{total_lines} lines")
        return

    if args.auto or args.run:
        asyncio.run(dream_auto())
    else:
        asyncio.run(dream_report())


if __name__ == "__main__":
    main()
