"""Tests for the shared ``## Processed`` decision-record coordination.

The proposal ``.md`` is the decision record shared with the multiplai-gui hub
(PR #29). These tests pin the cross-repo contract: the item-ref key scheme, the
``## Processed`` move (round-trip + idempotence), pending detection, and the CLI
verbs (``--mark-processed`` / ``--pending-view`` / ``--archive`` refusal).
"""

import os
import subprocess
import sys
from pathlib import Path

import pytest
from conftest import SCRIPTS_DIR

from lib import dream_processed as dp

DREAM_PY = SCRIPTS_DIR / "dream.py"

# The multiplai-gui hub's test fixture, copied verbatim so the parity assertions
# below check the same bytes the hub parses. If the hub fixture changes, this
# copy (and the contract) must be reconciled — see dream_processed.py's docstring.
HUB_FIXTURE = """# Processed Learnings — 2026-07-12

**Sources:** 2 files, ~8 entries
Generated by Dream. Review with `/multiplai-context:dream-remember` to apply.

---

## Updates for `testing.md` (2 learnings)

### 1. Clock mocking causes flaky retries
**Section:** Test Reliability
**Change:** add
> Retry tests must freeze the monotonic clock, not the wall clock — mixing
> the two produced the orbit-cli flake.

**Source:** 2026-07-12.md:3

### 2. Prefer fixture factories over shared fixtures
**Section:** Test Reliability
**Change:** update
> Shared mutable fixtures caused cross-test pollution twice; default to
> factory functions.

**Source:** 2026-07-12.md:9

---

## Updates for `build-tools.md` (2 learnings)

### 2. bun install needs a lockfile refresh after registry moves
**Section:** Bundlers
**Change:** add
> After a registry migration, delete bun.lockb and reinstall — stale
> integrity hashes fail silently.

**Source:** 2026-07-11.md:5

### 4. esbuild upgrade halves docs build time
**Section:** Bundlers
**Change:** add
> Upgrading esbuild majors is low-risk here; config surface unchanged since v0.19.

**Source:** 2026-07-11.md:2

---

## Action Items (2 items)

### A1. Fix flaky-retry harness: freeze the monotonic clock in CI
**What:** Add a monotonic-clock freeze fixture to the retry test harness.
**Why:** Wall-clock mocking alone reproduces the orbit-cli flake.
**Source:** 2026-07-12.md:14

### A3. Pin esbuild major in docs build
**What:** Pin esbuild to the current major in docs/package.json.
**Why:** Unpinned majors have broken the docs build twice.
**Source:** 2026-07-11.md:8

---

## Filtered Out (1 item)

- "one-off git stash confusion" (2026-07-12.md) — diary material, not a reusable lesson
"""

# The exact pending refs the fixture must parse to — the cross-writer contract.
EXPECTED_KEYS = [
    "update:testing.md#1",
    "update:testing.md#2",
    "update:build-tools.md#2",
    "update:build-tools.md#4",
    "action:A1",
    "action:A3",
]


# -- key scheme / parity --------------------------------------------------------


def test_pending_keys_match_hub_scheme():
    """Parity: the fixture parses to the exact hub key strings, including the
    per-file duplicate index (#2 under two files) and the non-contiguous
    action index (A3)."""
    keys = [dp.item_key(r) for r in dp.pending_items(HUB_FIXTURE)]
    assert keys == EXPECTED_KEYS
    # The two anchor keys the plan calls out explicitly.
    assert "update:testing.md#1" in keys
    assert "action:A1" in keys


def test_parse_ref_item_key_roundtrip():
    for key in EXPECTED_KEYS:
        assert dp.item_key(dp.parse_ref(key)) == key
    assert dp.parse_ref("update:memory/x.md#3") == ("update", "memory/x.md", 3)
    assert dp.parse_ref("action:A12") == ("action", 12)


@pytest.mark.parametrize("bad", ["bogus", "update:no-index", "action:AX", "update:#3", ""])
def test_parse_ref_rejects_malformed(bad):
    with pytest.raises(ValueError):
        dp.parse_ref(bad)


# -- move_to_processed round-trip / idempotence ---------------------------------


def test_applied_update_moves_to_processed():
    new = dp.move_to_processed(
        HUB_FIXTURE, ("update", "testing.md", 1), "applied",
        target="testing.md", ts="2026-07-23T00:00:00Z",
    )
    assert dp.PROCESSED_HEADING in new
    assert "**Processed:** applied → testing.md · 2026-07-23T00:00:00Z" in new
    # The block (its heading) is now below the processed heading, not above it.
    processed = new.split(dp.PROCESSED_HEADING)[1]
    assert "### 1. Clock mocking causes flaky retries" in processed
    # No longer pending; nothing else disturbed.
    after = [dp.item_key(r) for r in dp.pending_items(new)]
    assert after == [k for k in EXPECTED_KEYS if k != "update:testing.md#1"]


def test_move_is_idempotent():
    once = dp.move_to_processed(
        HUB_FIXTURE, ("update", "testing.md", 1), "applied", target="testing.md",
        ts="2026-07-23T00:00:00Z",
    )
    twice = dp.move_to_processed(
        once, ("update", "testing.md", 1), "applied", target="testing.md",
        ts="2026-07-23T00:00:00Z",
    )
    assert twice == once  # already processed → unchanged


def test_rejected_update_moves_without_target_annotation():
    new = dp.move_to_processed(
        HUB_FIXTURE, ("update", "testing.md", 2), "rejected", ts="2026-07-23T00:00:00Z",
    )
    assert "**Processed:** rejected · 2026-07-23T00:00:00Z" in new
    assert "→" not in new.split(dp.PROCESSED_HEADING)[1].split("**Processed:**")[1].splitlines()[0]
    assert ("update", "testing.md", 2) not in dp.pending_items(new)


def test_action_item_moves_to_processed():
    new = dp.move_to_processed(HUB_FIXTURE, ("action", 1), "applied", ts="2026-07-23T00:00:00Z")
    processed = new.split(dp.PROCESSED_HEADING)[1]
    assert "### A1. Fix flaky-retry harness" in processed
    assert ("action", 1) not in dp.pending_items(new)
    assert ("action", 3) in dp.pending_items(new)  # untouched action stays pending


# -- unprocessed / count_pending ------------------------------------------------


def _six_update_proposal() -> str:
    body = ["# Processed Learnings — test", "", "## Updates for `notes.md` (6 learnings)", ""]
    for i in range(1, 7):
        body += [f"### {i}. Item {i}", "**Change:** add", f"> content {i}", ""]
    return "\n".join(body) + "\n"


def test_unprocessed_after_deciding_1_and_2_returns_3_to_6():
    text = _six_update_proposal()
    assert dp.count_pending(text) == 6
    text = dp.move_to_processed(text, ("update", "notes.md", 1), "applied", target="notes.md")
    text = dp.move_to_processed(text, ("update", "notes.md", 2), "rejected")
    remaining = [r[2] for r in dp.pending_items(text)]
    assert remaining == [3, 4, 5, 6]
    assert dp.count_pending(text) == 4


# -- mark_processed file I/O ----------------------------------------------------


def test_mark_processed_writes_and_reports_change(tmp_path):
    p = tmp_path / "processed-learnings-2026-07-23.md"
    p.write_text(HUB_FIXTURE)
    changed = dp.mark_processed(p, ("update", "testing.md", 1), "applied", target="testing.md")
    assert changed is True
    assert "**Processed:** applied → testing.md" in p.read_text()
    # Second call is a no-op (already processed).
    assert dp.mark_processed(p, ("update", "testing.md", 1), "applied", target="testing.md") is False


# -- CLI: --pending-view / --mark-processed -------------------------------------


def _run_cli(args, workspace: Path):
    """Run dream.py with a controlled workspace (dreams under <ws>/.multiplai)."""
    env = os.environ.copy()
    for k in list(env):
        if k.startswith("CLAUDE_PLUGIN"):
            del env[k]
    env["WORKSPACE"] = str(workspace)
    return subprocess.run(
        [sys.executable, str(DREAM_PY), *args],
        capture_output=True, text=True, env=env, timeout=60,
    )


def test_cli_pending_view_and_mark_processed(tmp_path):
    p = tmp_path / "p.md"
    p.write_text(HUB_FIXTURE)

    r = _run_cli(["--pending-view", "--proposal", str(p)], tmp_path)
    assert r.returncode == 0, r.stderr
    assert "PENDING: 6" in r.stdout
    assert "update:testing.md#1" in r.stdout

    r = _run_cli(
        ["--mark-processed", "--proposal", str(p),
         "--ref", "update:testing.md#1", "--status", "applied", "--target", "testing.md"],
        tmp_path,
    )
    assert r.returncode == 0, r.stderr
    assert "**Processed:** applied → testing.md" in p.read_text()

    r = _run_cli(["--pending-view", "--proposal", str(p)], tmp_path)
    assert "PENDING: 5" in r.stdout


def test_cli_mark_processed_bad_ref_exits_nonzero(tmp_path):
    p = tmp_path / "p.md"
    p.write_text(HUB_FIXTURE)
    r = _run_cli(
        ["--mark-processed", "--proposal", str(p), "--ref", "bogus", "--status", "applied"],
        tmp_path,
    )
    assert r.returncode != 0


# -- CLI: --archive refusal (partial) and cleanup (full) ------------------------


def _dreams_root(workspace: Path) -> Path:
    d = workspace / ".multiplai" / "dreams"
    d.mkdir(parents=True, exist_ok=True)
    return d


def test_cli_archive_refuses_partial_proposal(tmp_path):
    dreams = _dreams_root(tmp_path)
    p = dreams / "p.md"
    p.write_text(HUB_FIXTURE)  # all 6 items still pending

    r = _run_cli(
        ["--stamp", "--files-updated", "0", "--learnings-processed", "0",
         "--archive", str(p)],
        tmp_path,
    )
    assert r.returncode != 0
    assert "still undecided" in r.stdout
    # Nothing moved; the .md is still in the dreams root.
    assert p.exists()
    assert not (dreams / "applied").exists()
    # A refused archive must not stamp dream_state either.
    assert not (tmp_path / ".multiplai" / "data" / "dream_state.yaml").exists()


def test_cli_archive_cleanup_on_fully_decided_proposal(tmp_path):
    dreams = _dreams_root(tmp_path)
    p = dreams / "p.md"
    # Decide every item first, in-process, so nothing is pending.
    text = HUB_FIXTURE
    for ref in (("update", "testing.md", 1), ("update", "testing.md", 2),
                ("update", "build-tools.md", 2), ("update", "build-tools.md", 4),
                ("action", 1), ("action", 3)):
        text = dp.move_to_processed(text, ref, "applied")
    p.write_text(text)
    assert dp.count_pending(p.read_text()) == 0

    r = _run_cli(
        ["--stamp", "--files-updated", "4", "--learnings-processed", "4",
         "--archive", str(p)],
        tmp_path,
    )
    assert r.returncode == 0, r.stderr
    assert not p.exists()  # moved out of the dreams root
    assert (dreams / "applied" / "p.md").exists()
