"""Tests for lib/proposal_merge.py — N chunk drafts into one proposal.

The merge is where chunking can lose a learning: a block consumed from the
backlog, recorded in the ledger, and then quietly missing from the document
nobody can compare against anything. So the assertions that matter are
conservation assertions — entry counts in equal entry counts out, and every
``**Source:**`` line from the inputs present verbatim in the output.

``split_by_file`` is deliberately tested against ``dream.py``'s documented
parsing behaviour rather than by importing ``dream.py``: the two must agree, and
restating the contract here is what catches a drift in either direction.
"""

from lib.proposal_merge import (
    count_entries,
    count_entries_in,
    merge_drafts,
    source_lines,
    split_by_file,
)

DRAFT_A = """\
# Processed Learnings — 2026-07-31

**Sources:** 2 files, ~40 entries
Generated by Dream. Review with `/multiplai-context:dream-remember` to apply.

---

## Updates for `dev.md`

### 1. Clean clone before open-sourcing
**Section:** Debugging Methodology
**Change:** add
> Simulate a clean clone before publishing a repo.

**Source:** 2026-07-27.md:12

### 2. Atomic writes for state files
**Section:** Data Patterns
**Change:** add
> Write state files temp-then-rename.

**Source:** 2026-07-27.md:40-42

---

## Action Items (1 items)

Changes the toolchain itself should make — NOT memory.

### A1. Lower the dream timeout
**What:** set MULTIPLAI_SDK_CALL_TIMEOUT_S to 900
**Why:** chunks are sized against it
**Source:** 2026-07-27.md:88

---

## Filtered Out (1 items)

- "renamed a branch": task residue
"""

DRAFT_B = """\
# Processed Learnings — 2026-07-31

**Sources:** 1 file

---

## Updates for `dev.md`

### 1. Worktrees by default
**Section:** Git Workflow
**Change:** add
> Non-trivial changes go in a worktree.

**Source:** 2026-07-28.md:7

---

## Updates for `claude-code-tools.md`

### 2. Hook output protocol
**Section:** Hooks
**Change:** add
> UserPromptSubmit hooks must emit hookSpecificOutput.

**Source:** 2026-07-28.md:19

---

## Action Items (1 items)

### A1. Add a run lock
**What:** flock the dream state dir
**Why:** two runs both write
**Source:** 2026-07-28.md:31

---

## Filtered Out (2 items)

- "fixed a typo": task residue
- "already applied": already applied
"""


class TestSplitByFile:
    def test_one_entry_per_target_file(self):
        assert set(split_by_file(DRAFT_B)) == {"dev.md", "claude-code-tools.md"}

    def test_section_body_keeps_its_own_heading(self):
        """dream.py's applier is fed this text and expects the header line."""
        assert split_by_file(DRAFT_B)["dev.md"].startswith("## Updates for `dev.md`")

    def test_other_h2_sections_are_not_targets(self):
        sections = split_by_file(DRAFT_A)
        assert "Action Items" not in sections
        assert "Filtered Out" not in sections

    def test_a_following_h2_terminates_the_section(self):
        assert "## Action Items" not in split_by_file(DRAFT_A)["dev.md"]
        assert "Lower the dream timeout" not in split_by_file(DRAFT_A)["dev.md"]

    def test_preamble_is_dropped(self):
        assert "Generated by Dream" not in "".join(split_by_file(DRAFT_A).values())

    def test_a_proposal_with_no_updates_yields_nothing(self):
        assert split_by_file("# Title\n\n## Filtered Out (0 items)\n\n- none\n") == {}

    def test_empty_input_yields_nothing(self):
        assert split_by_file("") == {}


class TestNoLoss:
    def test_entry_count_is_conserved(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert count_entries(merged) == count_entries_in([DRAFT_A, DRAFT_B]) == 6

    def test_every_source_line_survives_verbatim(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        expected = source_lines(DRAFT_A) + source_lines(DRAFT_B)
        assert sorted(source_lines(merged)) == sorted(expected)
        for line in expected:
            assert line in merged

    def test_entry_bodies_are_copied_verbatim(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        for text in ("> Write state files temp-then-rename.",
                     "**Section:** Debugging Methodology",
                     "> UserPromptSubmit hooks must emit hookSpecificOutput."):
            assert text in merged

    def test_filtered_out_items_all_survive(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert '- "renamed a branch": task residue' in merged
        assert '- "fixed a typo": task residue' in merged
        assert '- "already applied": already applied' in merged

    def test_filtered_out_count_is_restated(self):
        assert "## Filtered Out (3 items)" in merge_drafts([DRAFT_A, DRAFT_B])


class TestRenumbering:
    def test_updates_number_continuously_across_target_files(self):
        """One counter for the whole proposal — '#14' must name exactly one entry.

        Files are emitted in sorted order, so claude-code-tools.md takes 1 and
        dev.md continues from there rather than restarting.
        """
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        by_file = split_by_file(merged)
        assert [l for l in by_file["claude-code-tools.md"].splitlines()
                if l.startswith("### ")] == [
            "### 1. Hook output protocol",
        ]
        assert [l for l in by_file["dev.md"].splitlines()
                if l.startswith("### ")] == [
            "### 2. Clean clone before open-sourcing",
            "### 3. Atomic writes for state files",
            "### 4. Worktrees by default",
        ]

    def test_no_update_number_is_reused_across_the_document(self):
        """The property that matters, independent of sort order."""
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        numbers = [
            int(l.split(".")[0].removeprefix("### "))
            for l in merged.splitlines()
            if l.startswith("### ") and l.removeprefix("### ")[0].isdigit()
        ]
        assert numbers == list(range(1, len(numbers) + 1))

    def test_action_items_merge_and_renumber(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert "## Action Items (2 items)" in merged
        assert "### A1. Lower the dream timeout" in merged
        assert "### A2. Add a run lock" in merged

    def test_only_the_heading_line_changes(self):
        """A renumber that touched anything else could rewrite provenance."""
        merged = merge_drafts([DRAFT_B])
        assert "**Source:** 2026-07-28.md:19" in merged
        assert "### 1. Hook output protocol" in merged
        assert "### 2. Hook output protocol" not in merged


class TestStructure:
    def test_target_files_are_sorted(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert merged.index("## Updates for `claude-code-tools.md`") < merged.index(
            "## Updates for `dev.md`"
        )

    def test_draft_order_is_preserved_within_a_file(self):
        merged = merge_drafts([DRAFT_B, DRAFT_A])
        dev = split_by_file(merged)["dev.md"]
        assert dev.index("Worktrees by default") < dev.index("Clean clone")

    def test_preamble_comes_from_the_first_draft(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert merged.startswith("# Processed Learnings — 2026-07-31")
        assert "**Sources:** 2 files, ~40 entries" in merged

    def test_canonical_section_order(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert merged.index("## Updates for `dev.md`") < merged.index("## Action Items")
        assert merged.index("## Action Items") < merged.index("## Filtered Out")

    def test_action_items_intro_is_kept_once(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert merged.count("Changes the toolchain itself should make") == 1

    def test_output_is_deterministic(self):
        assert merge_drafts([DRAFT_A, DRAFT_B]) == merge_drafts([DRAFT_A, DRAFT_B])

    def test_result_is_reparseable_by_its_own_parser(self):
        """The merged document must round-trip — it is what dream writes out."""
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert count_entries(merge_drafts([merged])) == count_entries(merged)

    def test_unknown_sections_are_preserved_rather_than_dropped(self):
        extra = DRAFT_A + "\n---\n\n## Routing Warnings\n\n- something odd\n"
        assert "- something odd" in merge_drafts([extra])

    def test_document_ends_with_a_single_newline(self):
        merged = merge_drafts([DRAFT_A, DRAFT_B])
        assert merged.endswith("\n") and not merged.endswith("\n\n")


class TestDegenerateInput:
    def test_no_drafts(self):
        assert merge_drafts([]) == ""

    def test_only_blank_drafts(self):
        assert merge_drafts(["", "   \n"]) == ""

    def test_a_failed_chunk_contributes_nothing_but_loses_nothing(self):
        """A chunk that failed is skipped by dream; the merge must still emit
        every entry the surviving chunks produced."""
        merged = merge_drafts([DRAFT_A, "", DRAFT_B])
        assert count_entries(merged) == 6

    def test_single_draft_keeps_all_its_entries(self):
        assert count_entries(merge_drafts([DRAFT_A])) == count_entries(DRAFT_A) == 3

    def test_draft_with_no_action_items_emits_no_action_section(self):
        only_updates = DRAFT_A.split("## Action Items")[0]
        assert "## Action Items" not in merge_drafts([only_updates])
