"""Batched ``--mark-processed`` and the deterministic ``--gc-learnings``.

Why these exist. A `/dream-remember` review of a real proposal decides 50–70
items, and the pre-batch apply path spent one `uv run` cold start per item — a
fresh interpreter and environment check, to move text inside one local file. On 2026-07-24 a 70-item review applied five files and then ran out
of context mid-review. The batch path collapses that to one call per target
file; these tests hold it to producing *exactly* what the per-item path did.

Two contracts are asserted, not assumed:

1. **Batch == sequential.** Every writer of a decided proposal must agree
   byte-for-byte on what one looks like, or two tools reviewing the same file
   disagree about what is pending.
2. **Batch == the hub's independent writer.** ``tests/fixtures/`` holds a
   pending proposal and the document multiplai-gui's hub produces from it.
   ``proposal_processed_by_hub.md`` was generated by running the hub's own
   ``multiplai_hub.dreams.move_to_processed`` (from the multiplai-gui checkout)
   over ``proposal_pending.md`` with ts ``2026-07-31T09:00:00Z`` and the five
   decisions in :data:`FIXTURE_DECISIONS`, in canonical order. Regenerate it
   from the hub, never by hand — a hand-edited fixture asserts nothing.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import SCRIPTS_DIR
from lib.dream_processed import (
    Decision,
    mark_many_processed,
    mark_processed,
    move_many_to_processed,
    move_to_processed,
    order_decisions,
)

FIXTURES = Path(__file__).parent / "fixtures"
PENDING = (FIXTURES / "proposal_pending.md").read_text()
HUB_OUTPUT = (FIXTURES / "proposal_processed_by_hub.md").read_text()

TS = "2026-07-31T09:00:00Z"

# The decision set the hub fixture was generated from, in the order
# /dream-remember would emit it: all of one target file, then the next, then
# the action items.
FIXTURE_DECISIONS = [
    Decision("update", 1, "applied", file="git-policy.md", target="git-policy.md"),
    Decision("update", 2, "rejected", file="git-policy.md"),
    Decision("update", 1, "edited", file="technical-pref.md", target="technical-pref.md"),
    Decision("action", 1, "applied"),
    Decision("action", 2, "rejected"),
]

# The one place the two writers deliberately differ: the explanatory note under
# ``## Processed`` names the tools in the opposite order. Both modules' comments
# say the note is history that is never re-parsed; only the heading and the
# entries themselves are contract.
_NOTE_RE = re.compile(r"^_Items decided via .*restore it\._$", re.MULTILINE)


def _proposal(tmp_path, text=PENDING, name="processed-learnings-2026-07-31.md"):
    p = tmp_path / name
    p.write_text(text)
    return p


def _annotations(text):
    """Count `**Processed:**` *annotation lines* — the explanatory note under the
    heading mentions the marker too, and would otherwise be counted as an item."""
    return sum(1 for line in text.splitlines() if line.startswith("**Processed:**"))


def _sequential(text, decisions, ts=TS):
    """The same decisions applied one at a time, in the given order."""
    for d in decisions:
        text = move_to_processed(text, d.ref, d.status, target=d.target, ts=ts)
    return text


# ---------------------------------------------------------------------------
# Ordering
# ---------------------------------------------------------------------------


class TestOrderDecisions:
    def test_descending_index_within_a_group(self):
        ds = [
            Decision("update", 1, "applied", file="git-policy.md"),
            Decision("update", 2, "rejected", file="git-policy.md"),
        ]
        assert [d.index for d in order_decisions(ds)] == [2, 1]

    def test_groups_keep_first_appearance_order(self):
        # Sorting the groups instead would reorder the appended blocks and stop
        # the batch from matching the same decisions applied one at a time.
        ds = [
            Decision("update", 1, "applied", file="zzz.md"),
            Decision("action", 1, "applied"),
            Decision("update", 1, "applied", file="aaa.md"),
        ]
        assert [(d.kind, d.file) for d in order_decisions(ds)] == [
            ("update", "zzz.md"),
            ("action", None),
            ("update", "aaa.md"),
        ]

    def test_unsorted_input_orders_the_same_as_sorted(self):
        a = [
            Decision("update", 2, "applied", file="git-policy.md"),
            Decision("update", 1, "rejected", file="git-policy.md"),
        ]
        b = list(reversed(a))
        assert order_decisions(a) == order_decisions(b)


# ---------------------------------------------------------------------------
# Batch marking
# ---------------------------------------------------------------------------


class TestBatchMarking:
    def test_marks_every_decision_in_one_call(self, tmp_path):
        p = _proposal(tmp_path)
        marked, unchanged = mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
        assert (marked, unchanged) == (5, 0)
        out = p.read_text()
        # Every decided item now sits under ## Processed, none above it.
        head, _, tail = out.partition("## Processed")
        assert "### 1. Worktrees are the default" not in head
        assert "### A2. Garbage-collect" not in head
        assert _annotations(tail) == 5

    def test_spans_several_files_and_both_kinds(self, tmp_path):
        p = _proposal(tmp_path)
        mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
        tail = p.read_text().split("## Processed", 1)[1]
        assert "### 1. Worktrees are the default" in tail
        assert "### 1. Prefer uv over pip" in tail
        assert "### A1. Batch the mark-processed calls" in tail

    def test_already_processed_items_count_as_unchanged(self, tmp_path):
        p = _proposal(tmp_path)
        mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
        before = p.read_text()
        marked, unchanged = mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
        assert (marked, unchanged) == (0, 5)
        assert p.read_text() == before  # idempotent, and no rewrite

    def test_unsorted_indices_match_descending_order(self):
        descending = [
            Decision("update", 2, "rejected", file="git-policy.md"),
            Decision("update", 1, "applied", file="git-policy.md", target="git-policy.md"),
        ]
        unsorted = list(reversed(descending))
        assert (
            move_many_to_processed(PENDING, unsorted, ts=TS)
            == move_many_to_processed(PENDING, descending, ts=TS)
        )

    def test_batch_matches_the_same_decisions_applied_one_at_a_time(self):
        """The stop-and-ask gate: a batched call must not differ *in any way*
        from N single-flag calls, or two writers of the same proposal disagree
        about what a decided item looks like."""
        batched, _ = move_many_to_processed(PENDING, FIXTURE_DECISIONS, ts=TS)
        assert batched == _sequential(PENDING, order_decisions(FIXTURE_DECISIONS))

    def test_batch_matches_the_hub_writer_format(self):
        """Fixture test against multiplai-gui's independent native writer."""
        batched, _ = move_many_to_processed(PENDING, FIXTURE_DECISIONS, ts=TS)
        assert _NOTE_RE.sub("<note>", batched) == _NOTE_RE.sub("<note>", HUB_OUTPUT)

    def test_the_only_divergence_from_the_hub_is_the_note_line(self):
        # Stated explicitly so a future change that introduces a *second*
        # difference fails here rather than silently widening the gap.
        batched, _ = move_many_to_processed(PENDING, FIXTURE_DECISIONS, ts=TS)
        ours = batched.splitlines()
        theirs = HUB_OUTPUT.splitlines()
        assert len(ours) == len(theirs)
        differing = [i for i, (a, b) in enumerate(zip(ours, theirs)) if a != b]
        assert len(differing) == 1
        assert _NOTE_RE.match(ours[differing[0]])
        assert _NOTE_RE.match(theirs[differing[0]])

    def test_empty_batch_is_a_no_op(self, tmp_path):
        p = _proposal(tmp_path)
        assert mark_many_processed(p, [], ts=TS) == (0, 0)
        assert p.read_text() == PENDING


class TestBatchPartialFailure:
    def test_unwritable_target_leaves_the_file_byte_identical(self, tmp_path):
        d = tmp_path / "dreams"
        d.mkdir()
        p = _proposal(d)
        original = p.read_bytes()
        d.chmod(0o500)  # readable, not writable: mkstemp fails
        try:
            with pytest.raises(OSError):
                mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
            assert p.read_bytes() == original
        finally:
            d.chmod(0o700)

    def test_no_temp_file_is_left_behind(self, tmp_path):
        d = tmp_path / "dreams"
        d.mkdir()
        p = _proposal(d)
        mark_many_processed(p, FIXTURE_DECISIONS, ts=TS)
        assert [f.name for f in d.iterdir()] == [p.name]


class TestDecisionParsing:
    def test_defaults_kind_to_update(self):
        d = Decision.from_dict({"file": "a.md", "index": 1, "status": "applied"})
        assert d.kind == "update"

    def test_update_without_file_is_rejected(self):
        with pytest.raises(ValueError, match="needs a 'file'"):
            Decision.from_dict({"kind": "update", "index": 1, "status": "applied"})

    def test_bad_status_is_rejected(self):
        with pytest.raises(ValueError, match="status must be"):
            Decision.from_dict({"kind": "action", "index": 1, "status": "approve"})

    def test_hub_intent_vocabulary_is_not_accepted(self):
        # `approve`/`reject`/`edit` are the hub's *intent* words; this flag
        # records *outcomes*. Blurring them would log an unapplied item as done.
        for status in ("approve", "reject", "edit"):
            with pytest.raises(ValueError):
                Decision.from_dict({"kind": "action", "index": 1, "status": status})

    def test_bad_index_is_rejected(self):
        with pytest.raises(ValueError, match="index must be"):
            Decision.from_dict({"kind": "action", "index": "1", "status": "applied"})

    def test_boolean_index_is_rejected(self):
        with pytest.raises(ValueError, match="index must be"):
            Decision.from_dict({"kind": "action", "index": True, "status": "applied"})

    def test_non_object_is_rejected(self):
        with pytest.raises(ValueError, match="must be an object"):
            Decision.from_dict(["update", 1])


# ---------------------------------------------------------------------------
# CLI surface
# ---------------------------------------------------------------------------


def _run_dream(tmp_path, *args, stdin=None):
    env = os.environ.copy()
    env["WORKSPACE"] = str(tmp_path)
    return subprocess.run(
        [sys.executable, str(SCRIPTS_DIR / "dream.py"), *args],
        input=stdin,
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )


def _stamp_ts(text):
    return re.sub(r"\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ", "<TS>", text)


class TestSingleItemCliRegression:
    """The single-flag form is what already-installed skill versions call. The
    batch form is strictly additive; this is the guard that it stayed that way.
    """

    EXPECTED_TAIL = """\
---

## Processed

_Items decided via `/dream-remember` or the GUI, moved here so they are no longer pending. Kept for history; delete the `**Processed:**` line and move a block back up to restore it._

### 1. Worktrees are the default for non-trivial work
**Processed:** applied → git-policy.md · <TS>
**Section:** Branching
**Change:** add
> Any multi-file change goes on a branch in a worktree.

**Source:** 2026-07-30.md:12
"""

    def test_single_flag_invocation_is_unchanged(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(
            tmp_path, "--mark-processed", "--proposal", str(p),
            "--kind", "update", "--file", "git-policy.md", "--index", "1",
            "--status", "applied", "--target", "git-policy.md",
        )
        assert r.returncode == 0, r.stderr
        assert "Marked update git-policy.md#1 as applied" in r.stdout
        assert _stamp_ts(p.read_text()).endswith(self.EXPECTED_TAIL)

    def test_single_flag_action_item(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(
            tmp_path, "--mark-processed", "--proposal", str(p),
            "--kind", "action", "--index", "1", "--status", "rejected",
        )
        assert r.returncode == 0, r.stderr
        assert "Marked action A1 as rejected" in r.stdout
        assert "**Processed:** rejected · " in p.read_text()

    def test_still_reports_no_change_for_an_unknown_item(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(
            tmp_path, "--mark-processed", "--proposal", str(p),
            "--kind", "action", "--index", "99", "--status", "applied",
        )
        assert r.returncode == 0, r.stderr
        assert "No change" in r.stdout
        assert p.read_text() == PENDING


class TestBatchCli:
    def _payload(self):
        return json.dumps([
            {"kind": "update", "file": "git-policy.md", "index": 1,
             "status": "applied", "target": "git-policy.md"},
            {"kind": "update", "file": "git-policy.md", "index": 2, "status": "rejected"},
            {"kind": "update", "file": "technical-pref.md", "index": 1,
             "status": "edited", "target": "technical-pref.md"},
            {"kind": "action", "index": 1, "status": "applied"},
            {"kind": "action", "index": 2, "status": "rejected"},
        ])

    def test_stdin_array_marks_everything_in_one_call(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(
            tmp_path, "--mark-processed", "--proposal", str(p), "--decisions", "-",
            stdin=self._payload(),
        )
        assert r.returncode == 0, r.stderr
        assert "marked 5 processed, 0 unchanged" in r.stdout
        assert _annotations(p.read_text().split("## Processed", 1)[1]) == 5

    def test_batch_cli_equals_five_single_flag_calls(self, tmp_path):
        """Criterion 15: one batched call and N single-flag calls must produce
        the same file (timestamps normalized — the clock is not the contract)."""
        a = _proposal(tmp_path, name="A.md")
        b = _proposal(tmp_path, name="B.md")
        _run_dream(tmp_path, "--mark-processed", "--proposal", str(a),
                   "--decisions", "-", stdin=self._payload())
        for d in order_decisions(FIXTURE_DECISIONS):
            args = ["--mark-processed", "--proposal", str(b), "--kind", d.kind,
                    "--index", str(d.index), "--status", d.status]
            if d.file:
                args += ["--file", d.file]
            if d.target:
                args += ["--target", d.target]
            r = _run_dream(tmp_path, *args)
            assert r.returncode == 0, r.stderr
        assert _stamp_ts(a.read_text()) == _stamp_ts(b.read_text())

    def test_decisions_from_a_file(self, tmp_path):
        p = _proposal(tmp_path)
        payload = tmp_path / "decisions.json"
        payload.write_text(self._payload())
        r = _run_dream(tmp_path, "--mark-processed", "--proposal", str(p),
                       "--decisions", str(payload))
        assert r.returncode == 0, r.stderr
        assert "marked 5 processed" in r.stdout

    def test_malformed_json_exits_two_and_writes_nothing(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(tmp_path, "--mark-processed", "--proposal", str(p),
                       "--decisions", "-", stdin="not json")
        assert r.returncode == 2
        assert "ERROR: --decisions could not be read" in r.stdout
        assert p.read_text() == PENDING

    def test_invalid_decision_exits_two_and_writes_nothing(self, tmp_path):
        p = _proposal(tmp_path)
        r = _run_dream(tmp_path, "--mark-processed", "--proposal", str(p),
                       "--decisions", "-",
                       stdin='[{"kind":"update","index":1,"status":"applied"}]')
        assert r.returncode == 2
        assert p.read_text() == PENDING

    def test_missing_proposal_is_an_error(self, tmp_path):
        r = _run_dream(tmp_path, "--mark-processed", "--decisions", "-", stdin="[]")
        assert r.returncode == 2
        assert "needs --proposal" in r.stdout

    def test_unwritable_dir_exits_nonzero_leaving_the_proposal_intact(self, tmp_path):
        d = tmp_path / "dreams"
        d.mkdir()
        p = _proposal(d)
        original = p.read_bytes()
        d.chmod(0o500)
        try:
            r = _run_dream(tmp_path, "--mark-processed", "--proposal", str(p),
                           "--decisions", "-", stdin=self._payload())
            assert r.returncode == 1
            assert "proposal unchanged" in r.stdout
            assert p.read_bytes() == original
        finally:
            d.chmod(0o700)


# ---------------------------------------------------------------------------
# --gc-learnings
# ---------------------------------------------------------------------------


LEARNINGS_A = """\
## Session Learnings — 2026-07-29T10:00:00+00:00
Session: aaaaaaaa-0000-0000-0000-000000000000
- **[trust: verified]** PATTERN First lesson. → Target: dev.md — do the thing.

---
## Session Learnings — 2026-07-29T11:00:00+00:00
Session: aaaaaaaa-0000-0000-0000-000000000001
- **[trust: high]** OBSERVATION Second lesson. → Target: life.md — note it.

---
"""

LEARNINGS_B = """\
## Session Learnings — 2026-07-30T10:00:00+00:00
Session: bbbbbbbb-0000-0000-0000-000000000000
- **[trust: verified]** PATTERN Third lesson. → Target: dev.md — do the other thing.

---
"""


class _StubPaths:
    def __init__(self, root):
        self.learnings_dir = root / "learnings"
        self._dreams = root / "dreams"

    def dreams_dir(self):
        self._dreams.mkdir(parents=True, exist_ok=True)
        return self._dreams


@pytest.fixture
def gc_env(tmp_path, monkeypatch):
    """dream.py wired to a scratch workspace, with a real ledger file."""
    from lib import learnings_ledger

    from test_dream_skill import _load_dream_module

    dream = _load_dream_module()
    paths = _StubPaths(tmp_path)
    paths.learnings_dir.mkdir(parents=True)
    paths.dreams_dir()
    ledger_path = tmp_path / "ledger.json"
    monkeypatch.setattr(dream, "get_paths", lambda: paths)
    monkeypatch.setattr(learnings_ledger, "default_ledger_path", lambda: ledger_path)
    return {
        "dream": dream,
        "ledger_path": ledger_path,
        "learnings": paths.learnings_dir,
        "dreams": paths._dreams,
        "ledger": learnings_ledger,
    }


def _write_learnings(env, name, text):
    p = env["learnings"] / name
    p.write_text(text)
    return p


def _ledger_all(env, name, proposal):
    """Record every block of a learnings file against *proposal*."""
    p = env["learnings"] / name
    blocks = env["ledger"].parse_blocks(name, p.read_text())
    env["ledger"].record(env["ledger_path"], blocks, proposal)
    return blocks


def _archive(env, proposal, disposition="applied", body="x"):
    """Put a proposal where a *decided* one lives.

    gc requires positive evidence of a decision, so a test that means "this
    proposal was reviewed" has to say so by putting the file somewhere — a
    ledgered name with no file anywhere is the crashed-run state, not a
    decided one.
    """
    d = env["dreams"] / disposition
    d.mkdir(parents=True, exist_ok=True)
    (d / proposal).write_text(body)
    return d / proposal


class TestGcLearnings:
    def test_deletes_a_fully_ledgered_file_whose_proposal_is_archived(self, gc_env, capsys):
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "processed-learnings-2026-07-29.md")
        (gc_env["dreams"] / "applied").mkdir()
        (gc_env["dreams"] / "applied" / "processed-learnings-2026-07-29.md").write_text("x")

        gc_env["dream"]._gc_learnings()

        assert not (gc_env["learnings"] / "2026-07-29.md").exists()
        out = capsys.readouterr().out
        assert "GC learnings: deleted 1, kept 0" in out

    def test_keeps_a_file_with_one_unledgered_block(self, gc_env, capsys):
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        blocks = gc_env["ledger"].parse_blocks("2026-07-29.md", LEARNINGS_A)
        gc_env["ledger"].record(gc_env["ledger_path"], blocks[:1], "p.md")

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        out = capsys.readouterr().out
        assert "GC learnings: deleted 0, kept 1" in out
        assert "1/2 record(s) not yet consolidated" in out

    def test_keeps_a_file_whose_proposal_is_still_pending(self, gc_env, capsys):
        # Load-bearing beyond retention: the pending proposal's
        # `**Source:** <file>:<line>` citations must still resolve for whoever
        # is reviewing it.
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "processed-learnings-2026-07-29.md")
        (gc_env["dreams"] / "processed-learnings-2026-07-29.md").write_text("pending")

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        out = capsys.readouterr().out
        assert "proposal still pending review: processed-learnings-2026-07-29.md" in out

    def test_empty_ledger_deletes_nothing(self, gc_env, capsys):
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _write_learnings(gc_env, "2026-07-30.md", LEARNINGS_B)

        gc_env["dream"]._gc_learnings()

        assert len(list(gc_env["learnings"].glob("*.md"))) == 2
        assert "GC learnings: deleted 0, kept 2" in capsys.readouterr().out

    def test_deletes_only_the_decided_file(self, gc_env, capsys):
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _write_learnings(gc_env, "2026-07-30.md", LEARNINGS_B)
        _ledger_all(gc_env, "2026-07-29.md", "old.md")
        _ledger_all(gc_env, "2026-07-30.md", "new.md")
        # old.md must actually be *somewhere* decided. Ledgering a name and
        # leaving the file nowhere used to read as "decided"; that is the
        # in-flight/crashed-run window, and gc now keeps those sources.
        _archive(gc_env, "old.md")
        (gc_env["dreams"] / "new.md").write_text("pending")

        gc_env["dream"]._gc_learnings()

        assert not (gc_env["learnings"] / "2026-07-29.md").exists()
        assert (gc_env["learnings"] / "2026-07-30.md").exists()
        assert "GC learnings: deleted 1, kept 1" in capsys.readouterr().out

    def test_prunes_ledger_keys_for_deleted_files(self, gc_env):
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "old.md")
        _archive(gc_env, "old.md")
        assert len(gc_env["ledger"].load(gc_env["ledger_path"])["processed"]) == 2

        gc_env["dream"]._gc_learnings()

        assert gc_env["ledger"].load(gc_env["ledger_path"])["processed"] == {}

    def test_keeps_a_file_with_no_parsable_records(self, gc_env, capsys):
        _write_learnings(gc_env, "notes.md", "just some prose, no records\n")

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "notes.md").exists()
        assert "no `## Session Learnings` records" in capsys.readouterr().out

    def test_no_learnings_directory_is_not_an_error(self, gc_env, capsys):
        for f in gc_env["learnings"].glob("*"):
            f.unlink()
        gc_env["dream"]._gc_learnings()
        assert "no learnings files" in capsys.readouterr().out

    def test_cli_flag_is_wired(self, tmp_path):
        r = _run_dream(tmp_path, "--gc-learnings")
        assert r.returncode == 0, r.stderr
        assert "GC learnings" in r.stdout


class TestGcDoesNotEatLiveInputs:
    """Regression tests for the two ways gc used to delete files still in use.

    Both were reported against #102 and both are unrecoverable in the moment
    (the mitigant is that learnings files are git-tracked *once committed*).
    Neither scenario had any coverage.
    """

    # --- #112: ledgered before the proposal file exists ---------------------

    def test_keeps_sources_of_a_run_still_in_flight(self, gc_env, capsys):
        """The window between "chunk ledgered" and "proposal written".

        _draft_chunk records blocks per chunk as it goes; the proposal is only
        written when the whole run finishes, potentially many minutes later.
        In between, the name is fully ledgered and the file exists nowhere.
        """
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "processed-learnings-2026-07-29.md")
        # No proposal anywhere: not in the root, not in applied/rejected/superseded.

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        assert "proposal not yet written" in capsys.readouterr().out

    def test_keeps_sources_of_a_crashed_run(self, gc_env, capsys):
        """Same state as in-flight, but permanent — the run died.

        The resumed run rebuilds from staged drafts and writes a proposal that
        cites these files, so deleting them breaks the resume.
        """
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _write_learnings(gc_env, "2026-07-30.md", LEARNINGS_B)
        _ledger_all(gc_env, "2026-07-29.md", "crashed-run.md")
        _ledger_all(gc_env, "2026-07-30.md", "crashed-run.md")

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        assert (gc_env["learnings"] / "2026-07-30.md").exists()
        assert "GC learnings: deleted 0, kept 2" in capsys.readouterr().out

    def test_a_decided_proposal_is_still_collected(self, gc_env, capsys):
        """The guard must not simply stop gc working — rejected/ counts too."""
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "reviewed.md")
        _archive(gc_env, "reviewed.md", "rejected")

        gc_env["dream"]._gc_learnings()

        assert not (gc_env["learnings"] / "2026-07-29.md").exists()
        assert "GC learnings: deleted 1, kept 0" in capsys.readouterr().out

    # --- #111: folded forward, ledger left pointing at the predecessor ------

    def test_keeps_sources_a_pending_successor_still_cites(self, gc_env, capsys):
        """P1 folded into P2: P1 lands in superseded/, so by the ledger alone
        its sources look decided — while P2 sits pending and cites them."""
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "p1.md")
        _archive(gc_env, "p1.md", "superseded")
        (gc_env["dreams"] / "p2.md").write_text(
            "## Updates\n\n- something learned\n\n**Source:** 2026-07-29.md:12\n"
        )

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        assert "still cited by a pending proposal" in capsys.readouterr().out

    def test_the_inline_filtered_out_citation_form_also_protects(self, gc_env):
        """`(Source: f.md:12)` is the other form the template emits. A check
        that saw only the bold form would protect strictly less than it looks."""
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "p1.md")
        _archive(gc_env, "p1.md", "superseded")
        (gc_env["dreams"] / "p2.md").write_text(
            "## Filtered Out\n\n- too specific (Source: 2026-07-29.md:12)\n"
        )

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()

    def test_an_uncited_sibling_is_still_collected(self, gc_env):
        """Citation protection is per file, not a blanket stop."""
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _write_learnings(gc_env, "2026-07-30.md", LEARNINGS_B)
        _ledger_all(gc_env, "2026-07-29.md", "p1.md")
        _ledger_all(gc_env, "2026-07-30.md", "p1.md")
        _archive(gc_env, "p1.md", "superseded")
        (gc_env["dreams"] / "p2.md").write_text("**Source:** 2026-07-29.md:12\n")

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        assert not (gc_env["learnings"] / "2026-07-30.md").exists()

    def test_an_unreadable_pending_proposal_stops_deletion_entirely(
        self, gc_env, capsys, monkeypatch
    ):
        """Fail closed: if we cannot read what a pending proposal cites, we
        cannot claim anything is uncited."""
        _write_learnings(gc_env, "2026-07-29.md", LEARNINGS_A)
        _ledger_all(gc_env, "2026-07-29.md", "p1.md")
        _archive(gc_env, "p1.md")
        bad = gc_env["dreams"] / "unreadable.md"
        bad.write_text("x")

        real_read = Path.read_text

        def boom(self, *a, **k):
            if self.name == "unreadable.md":
                raise OSError("nope")
            return real_read(self, *a, **k)

        monkeypatch.setattr(Path, "read_text", boom)

        gc_env["dream"]._gc_learnings()

        assert (gc_env["learnings"] / "2026-07-29.md").exists()
        assert "nothing deleted this pass" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# SKILL.md — the apply path must be per-file, not per-item
# ---------------------------------------------------------------------------


SKILL = (Path(__file__).parent.parent / "skills" / "dream-remember" / "SKILL.md").read_text()


class TestSkillIsBatched:
    def test_at_most_three_mark_processed_mentions(self):
        # Criterion 17: per-file updates, action items, and the preamble
        # reference. A fourth line means a per-item invocation crept back.
        assert sum(1 for line in SKILL.splitlines() if "mark-processed" in line) <= 3

    def test_uses_the_batched_decisions_form(self):
        assert "--decisions -" in SKILL

    def test_rule_proposals_are_still_one_at_a_time(self):
        # Batching is for mechanics, never for consent.
        assert "RULE-PROPOSAL" in SKILL
        assert "one at a time" in SKILL

    def test_step_five_runs_the_gc_and_deletes_nothing_by_hand(self):
        step5 = SKILL.split("## Step 5")[1].split("## Step 6")[0]
        assert "--gc-learnings" in step5
        assert not re.search(r"\brm\b|\bDelete ALL\b|\bunlink\b", step5)


def test_marker_is_used_by_nothing_else():
    """`mark_processed` (single) is still exported — older installed skills and
    any external caller import it by name."""
    assert callable(mark_processed)
