"""Tests for dream's batching pipeline — the lock, the single-proposal fold, and
per-chunk staging/resume.

These cover the parts of `dream.py` that decide *whether* work happens and *what
survives a crash*. The pure libraries they lean on (`learnings_ledger`,
`dream_chunking`, `proposal_merge`, `proposal_edits`) have their own unit suites;
nothing here re-tests those.

Two properties are asserted hardest because getting them wrong is unrecoverable:

- a proposal a human has edited is NEVER folded (hand-curation is a supported
  workflow — Spike approves by deleting the items he does not want — and folding
  such a file destroys the curation), and the guard keys on CONTENT, not mtime,
  because `.multiplai/dreams/` is git-tracked and checkout rewrites mtimes;
- a block is never left recorded in the ledger when its draft did not reach the
  merge. That is silent learning loss: the block never resurfaces and nobody
  ever sees it.
"""

import asyncio
import importlib.util
import json
import os
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from conftest import PLUGIN_ROOT, SCRIPTS_DIR


def _load_dream(alias: str):
    """Load dream.py as an isolated module (fresh paths cache) per test."""
    from multiplai_core.paths import _reset_cache

    _reset_cache()
    spec = importlib.util.spec_from_file_location(alias, SCRIPTS_DIR / "dream.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def dream_env(tmp_path, monkeypatch):
    """A dream workspace rooted at tmp_path, with paths resolved fresh."""
    data_dir = tmp_path / "data"
    memory_dir = tmp_path / "memory"
    for d in (data_dir, memory_dir, data_dir / "catalogs"):
        d.mkdir(parents=True, exist_ok=True)

    monkeypatch.setenv("CLAUDE_PLUGIN_DATA", str(data_dir))
    monkeypatch.setenv("CLAUDE_PLUGIN_ROOT", str(PLUGIN_ROOT))
    monkeypatch.setenv("CLAUDE_PLUGIN_OPTION_memory_dir", str(memory_dir))

    from multiplai_core.paths import _reset_cache, get_paths

    _reset_cache()
    paths = get_paths()
    paths.learnings_dir.mkdir(parents=True, exist_ok=True)
    paths.dreams_dir().mkdir(parents=True, exist_ok=True)
    (memory_dir / "dev.md").write_text("# Dev\n\n## Tooling\n")
    return {
        "data_dir": data_dir,
        "memory_dir": memory_dir,
        "learnings_dir": paths.learnings_dir,
        "dreams_dir": paths.dreams_dir(),
    }


# A proposal shaped exactly like what dream writes: one pending update entry
# with its provenance line. `has_pending_items` needs the `## Updates for`
# grouping to see anything at all.
PROPOSAL_BODY = """\
# Processed Learnings — 2026-07-30

**Sources:** 1 files, ~2 entries
Generated by Dream. Review with `/multiplai-context:dream-remember` to apply.

---

## Updates for `dev.md`

### 1. Always fetch before comparing to a remote
**Section:** Tooling
**Change:** add
> Run `git fetch` before checking ahead/behind counts.

**Source:** 2026-07-30.md:12

---

## Filtered Out (1 items)

**diary/event-only**
- Shipped the thing — records what happened (Source: 2026-07-30.md:20)
"""

DECIDED_BODY = PROPOSAL_BODY + """
---

## Processed

_Items decided via `/dream-remember` or the GUI._

### 2. A decided entry
**Processed:** applied → dev.md · 2026-07-30T10:00:00Z
**Source:** 2026-07-30.md:30
"""


def _write_generated(mod, dreams_dir: Path, name: str, body: str = PROPOSAL_BODY) -> Path:
    path = dreams_dir / name
    path.write_text(mod._stamp_generated(body))
    return path


# ---------------------------------------------------------------------------
# The run lock
# ---------------------------------------------------------------------------


class TestRunLock:
    """A second concurrent run is a no-op, not an error."""

    def test_second_acquisition_is_refused(self, dream_env, capsys):
        mod = _load_dream("dream_lock_basic")
        assert mod.acquire_run_lock() is True
        # flock is per open file description, so a second open() in this same
        # process contends exactly as another container's process would.
        assert mod.acquire_run_lock() is False
        out = capsys.readouterr().out
        assert "Another dream run is already in progress" in out
        assert "started" in out, "the message must name the holder's start time"

    def test_lock_file_carries_an_iso_start_time(self, dream_env):
        mod = _load_dream("dream_lock_stamp")
        assert mod.acquire_run_lock() is True
        from datetime import datetime

        stamp = mod._lock_path().read_text().strip()
        # Round-trips as an ISO timestamp — that string is what the contention
        # message shows the second run.
        assert datetime.fromisoformat(stamp)

    def test_lock_lives_in_the_workspace_not_tmp(self, dream_env):
        """A /tmp lock is container-local — two sessions would both proceed."""
        mod = _load_dream("dream_lock_path")
        assert mod.acquire_run_lock() is True
        assert str(mod._lock_path()).startswith(str(dream_env["data_dir"]))

    def test_second_report_run_exits_without_writing_a_proposal(self, dream_env):
        mod = _load_dream("dream_lock_report")
        assert mod.acquire_run_lock() is True

        client = AsyncMock()
        mod.create_client = AsyncMock(return_value=client)
        asyncio.run(mod.dream_report())

        client.query.assert_not_awaited()
        assert list(dream_env["dreams_dir"].glob("*.md")) == []

    def test_check_answers_while_a_run_holds_the_lock(self, dream_env, capsys, monkeypatch):
        """--check must work mid-run — that is most of the point of having it."""
        mod = _load_dream("dream_lock_check")
        (dream_env["learnings_dir"] / "2026-07-30.md").write_text(
            "## Session Learnings — 2026-07-30T01:00:00+00:00\n"
            "Session: s1\n- **[trust: verified]** PATTERN A lesson. → Target: dev.md\n"
        )
        assert mod.acquire_run_lock() is True
        capsys.readouterr()

        monkeypatch.setattr("sys.argv", ["dream.py", "--check"])
        mod.main()

        out = capsys.readouterr().out
        assert "Another dream run is already in progress" not in out
        assert "Pending learnings:" in out
        assert "Dream plan:" in out
        assert "Estimated wall clock:" in out


# ---------------------------------------------------------------------------
# The `dream:generated` stamp
# ---------------------------------------------------------------------------


class TestGeneratedStamp:
    def test_stamp_round_trips(self, dream_env):
        mod = _load_dream("dream_stamp")
        stamped = mod._stamp_generated(PROPOSAL_BODY)
        assert mod._is_unmodified_generated(stamped)
        assert stamped.rstrip().endswith("-->")

    def test_any_edit_breaks_the_hash(self, dream_env):
        mod = _load_dream("dream_stamp_edit")
        stamped = mod._stamp_generated(PROPOSAL_BODY)
        edited = stamped.replace("Always fetch", "Always FETCH")
        assert not mod._is_unmodified_generated(edited)

    def test_unstamped_document_never_passes(self, dream_env):
        """Pre-ledger proposals carry no stamp — left alone by design."""
        mod = _load_dream("dream_stamp_none")
        assert not mod._is_unmodified_generated(PROPOSAL_BODY)


# ---------------------------------------------------------------------------
# One pending proposal, enforced
# ---------------------------------------------------------------------------


class TestFoldPendingProposals:
    def test_undecided_generated_proposal_is_folded_and_superseded(self, dream_env):
        mod = _load_dream("dream_fold_ok")
        dreams_dir = dream_env["dreams_dir"]
        path = _write_generated(mod, dreams_dir, "processed-learnings-2026-07-30.md")

        folded = mod._fold_pending_proposals(dreams_dir)

        assert len(folded) == 1
        assert "Always fetch before comparing to a remote" in folded[0]
        assert not path.exists(), "the folded proposal must leave the dreams root"
        superseded = list((dreams_dir / "superseded").glob("*.md"))
        assert [p.name for p in superseded] == ["processed-learnings-2026-07-30.md"]

    def test_proposal_with_processed_items_is_left_strictly_alone(self, dream_env):
        """`## Processed` is the cross-tool contract — folding discards decisions."""
        mod = _load_dream("dream_fold_decided")
        dreams_dir = dream_env["dreams_dir"]
        path = _write_generated(mod, dreams_dir, "processed-learnings-2026-07-30.md",
                                DECIDED_BODY)

        assert mod._fold_pending_proposals(dreams_dir) == []
        assert path.exists()
        assert not (dreams_dir / "superseded").exists()

    def test_hand_curated_proposal_is_not_folded(self, dream_env):
        """Spike curates by deleting items; the remainder IS the approval."""
        mod = _load_dream("dream_fold_curated")
        dreams_dir = dream_env["dreams_dir"]
        path = _write_generated(mod, dreams_dir, "processed-learnings-2026-07-30.md")
        curated = path.read_text().replace(
            "> Run `git fetch` before checking ahead/behind counts.\n", ""
        )
        path.write_text(curated)

        assert mod._fold_pending_proposals(dreams_dir) == []
        assert path.exists()
        assert path.read_text() == curated, "a curated proposal must not be touched"

    def test_touched_but_unchanged_proposal_is_still_folded(self, dream_env):
        """mtime is not the criterion: git checkout/stash rewrite mtimes."""
        mod = _load_dream("dream_fold_touched")
        dreams_dir = dream_env["dreams_dir"]
        path = _write_generated(mod, dreams_dir, "processed-learnings-2026-07-30.md")
        before = path.read_bytes()
        os.utime(path, (0, 0))
        assert path.stat().st_mtime == 0

        folded = mod._fold_pending_proposals(dreams_dir)

        assert len(folded) == 1
        assert not path.exists()
        assert (dreams_dir / "superseded" /
                "processed-learnings-2026-07-30.md").read_bytes() == before

    def test_pre_ledger_proposal_without_stamp_is_not_folded(self, dream_env):
        mod = _load_dream("dream_fold_preledger")
        dreams_dir = dream_env["dreams_dir"]
        path = dreams_dir / "processed-learnings-2026-07-29.md"
        path.write_text(PROPOSAL_BODY)

        assert mod._fold_pending_proposals(dreams_dir) == []
        assert path.exists()

    def test_superseding_is_collision_safe(self, dream_env):
        mod = _load_dream("dream_fold_collide")
        dreams_dir = dream_env["dreams_dir"]
        (dreams_dir / "superseded").mkdir()
        (dreams_dir / "superseded" / "processed-learnings-2026-07-30.md").write_text("old")
        _write_generated(mod, dreams_dir, "processed-learnings-2026-07-30.md")

        assert len(mod._fold_pending_proposals(dreams_dir)) == 1
        names = sorted(p.name for p in (dreams_dir / "superseded").glob("*.md"))
        assert names == [
            "processed-learnings-2026-07-30.md",
            "processed-learnings-2026-07-30-2.md",
        ] or names == [
            "processed-learnings-2026-07-30-2.md",
            "processed-learnings-2026-07-30.md",
        ]
        assert (dreams_dir / "superseded" /
                "processed-learnings-2026-07-30.md").read_text() == "old"


# ---------------------------------------------------------------------------
# Per-chunk staging and resume
# ---------------------------------------------------------------------------


def _blocks(mod, count: int = 2):
    from lib.learnings_ledger import parse_blocks

    text = "\n".join(
        f"## Session Learnings — 2026-07-30T0{i}:00:00+00:00\n"
        f"Session: abc-{i}\n"
        f"- **[trust: verified]** PATTERN Lesson {i}. → Target: dev.md\n\n---\n"
        for i in range(count)
    )
    return parse_blocks("2026-07-30.md", text)


class TestStagingAndResume:
    def test_staged_draft_and_sidecar_are_written(self, dream_env):
        mod = _load_dream("dream_stage")
        run_dir = mod._runs_dir() / "run-a"
        blocks = _blocks(mod, 1)

        md = mod._stage_draft(run_dir, 3, "DRAFT", [b.key for b in blocks])

        assert md.name == "chunk-03.md"
        assert md.read_text() == "DRAFT"
        meta = json.loads((run_dir / "chunk-03.json").read_text())
        assert meta["keys"] == [blocks[0].key]

    def test_ledgered_staged_draft_is_resumed(self, dream_env):
        mod = _load_dream("dream_resume_ok")
        blocks = _blocks(mod, 1)
        old_run = mod._runs_dir() / "run-old"
        mod._stage_draft(old_run, 1, "STAGED DRAFT", [b.key for b in blocks])

        ledger_path = mod.learnings_ledger.default_ledger_path()
        mod.learnings_ledger.record(ledger_path, blocks, "processed-learnings-x.md")
        ledger = mod.learnings_ledger.load(ledger_path)

        resumed = mod._resume_staged_drafts(mod._runs_dir() / "run-new", ledger)

        assert resumed == ["STAGED DRAFT"]

    def test_unledgered_staged_draft_is_discarded(self, dream_env):
        """Its blocks are being re-drafted now — keeping it would duplicate them."""
        mod = _load_dream("dream_resume_stale")
        blocks = _blocks(mod, 1)
        old_run = mod._runs_dir() / "run-old"
        md = mod._stage_draft(old_run, 1, "STALE", [b.key for b in blocks])

        ledger = {"version": 1, "processed": {}}
        assert mod._resume_staged_drafts(mod._runs_dir() / "run-new", ledger) == []
        assert not md.exists()

    def test_keyless_draft_is_always_resumed(self, dream_env):
        """A folded proposal has no blocks; it must survive a crashed run."""
        mod = _load_dream("dream_resume_folded")
        old_run = mod._runs_dir() / "run-old"
        mod._stage_draft(old_run, 1, "FOLDED", [], kind="folded")

        ledger = {"version": 1, "processed": {}}
        assert mod._resume_staged_drafts(mod._runs_dir() / "run-new", ledger) == ["FOLDED"]

    def test_current_run_dir_is_not_resumed(self, dream_env):
        mod = _load_dream("dream_resume_self")
        run_dir = mod._runs_dir() / "run-now"
        mod._stage_draft(run_dir, 1, "MINE", [])
        assert mod._resume_staged_drafts(run_dir, {"processed": {}}) == []

    def test_clear_staging_removes_every_run_dir(self, dream_env):
        mod = _load_dream("dream_clear")
        mod._stage_draft(mod._runs_dir() / "run-a", 1, "A", [])
        mod._stage_draft(mod._runs_dir() / "run-b", 1, "B", [])
        mod._clear_staging()
        assert list(mod._runs_dir().iterdir()) == []


# ---------------------------------------------------------------------------
# The hard invariant: recorded ⇒ present in the merge
# ---------------------------------------------------------------------------


class TestLedgerCoverage:
    def test_a_dropped_draft_un_records_its_blocks(self, dream_env):
        """Recording a block whose draft never reached the merge is silent loss."""
        mod = _load_dream("dream_coverage_bad")
        blocks = _blocks(mod, 1)
        run_dir = mod._runs_dir() / "run-a"
        mod._stage_draft(run_dir, 1, "DRAFT A", [b.key for b in blocks])
        ledger_path = mod.learnings_ledger.default_ledger_path()
        mod.learnings_ledger.record(ledger_path, blocks, "p.md")

        # Merge input does NOT contain the staged draft.
        mod._enforce_ledger_coverage(ledger_path, run_dir, ["something else"])

        ledger = mod.learnings_ledger.load(ledger_path)
        assert blocks[0].key not in ledger["processed"], (
            "a block whose draft was dropped must be re-consolidated next run"
        )

    def test_a_merged_draft_keeps_its_record(self, dream_env):
        mod = _load_dream("dream_coverage_ok")
        blocks = _blocks(mod, 1)
        run_dir = mod._runs_dir() / "run-a"
        mod._stage_draft(run_dir, 1, "DRAFT A", [b.key for b in blocks])
        ledger_path = mod.learnings_ledger.default_ledger_path()
        mod.learnings_ledger.record(ledger_path, blocks, "p.md")

        mod._enforce_ledger_coverage(ledger_path, run_dir, ["DRAFT A"])

        assert blocks[0].key in mod.learnings_ledger.load(ledger_path)["processed"]


# ---------------------------------------------------------------------------
# Chunked draft: failure is per chunk, unless it is total
# ---------------------------------------------------------------------------


def _chunks(mod, n: int):
    """Real Chunk objects, one block each, so `render_chunk` has real input."""
    from lib.dream_chunking import Chunk

    blocks = _blocks(mod, n)
    return [
        Chunk(
            index=i + 1,
            blocks=(b,),
            n_bytes=len(b.text.encode("utf-8")),
            timeout_s=mod.CHUNK_TIMEOUT_S,
            oversized=False,
        )
        for i, b in enumerate(blocks)
    ]


def _client(responses):
    """A client whose query() returns/raises the next item of *responses*."""
    calls = []

    async def query(*, system, messages, **kwargs):
        item = responses[len(calls)]
        calls.append(kwargs)
        if isinstance(item, Exception):
            raise item
        response = MagicMock()
        response.content = item
        return response

    client = MagicMock()
    client.query = query
    client.calls = calls
    return client


async def _draft(mod, client, chunks, run_dir):
    return await mod._draft_chunks(
        client, chunks,
        memory_context="### dev.md\nSECTIONS:\n# Dev",
        source_names="2026-07-30.md",
        run_dir=run_dir,
        ledger_path=mod.learnings_ledger.default_ledger_path(),
        proposal_name="processed-learnings-2026-07-30.md",
    )


class TestChunkedDraft:
    def test_one_failed_chunk_is_skipped_and_stays_unprocessed(self, dream_env):
        mod = _load_dream("dream_chunk_partial")
        chunks = _chunks(mod, 2)
        client = _client([RuntimeError("boom"), "## Updates for `dev.md`\n\n### 1. ok\n"])
        run_dir = mod._runs_dir() / "run-a"

        drafts = asyncio.run(_draft(mod, client, chunks, run_dir))

        assert len(drafts) == 1
        processed = mod.learnings_ledger.load(
            mod.learnings_ledger.default_ledger_path()
        )["processed"]
        assert chunks[0].blocks[0].key not in processed, (
            "a failed chunk's blocks must stay unprocessed for the next run"
        )
        assert chunks[1].blocks[0].key in processed

    def test_every_chunk_failing_re_raises(self, dream_env):
        """A total failure is an outage — writing an empty proposal would look
        like success."""
        mod = _load_dream("dream_chunk_total")
        chunks = _chunks(mod, 2)
        client = _client([RuntimeError("boom"), RuntimeError("boom")])

        with pytest.raises(RuntimeError):
            asyncio.run(_draft(mod, client, chunks, mod._runs_dir() / "run-a"))

    def test_successful_chunks_are_staged_before_the_run_ends(self, dream_env):
        mod = _load_dream("dream_chunk_stage")
        chunks = _chunks(mod, 2)
        client = _client(["DRAFT ONE", "DRAFT TWO"])
        run_dir = mod._runs_dir() / "run-a"

        asyncio.run(_draft(mod, client, chunks, run_dir))

        staged = sorted(p.name for p in run_dir.glob("*.md"))
        assert staged == ["chunk-01.md", "chunk-02.md"]

    def test_per_chunk_timeout_is_passed_through(self, dream_env):
        mod = _load_dream("dream_chunk_timeout")
        chunks = _chunks(mod, 1)
        client = _client(["DRAFT"])

        asyncio.run(_draft(mod, client, chunks, mod._runs_dir() / "run-a"))

        assert client.calls[0].get("timeout_s") == chunks[0].timeout_s

    def test_older_core_without_timeout_kwarg_still_works(self, dream_env):
        """PR B adds query(timeout_s=…); an older pin must not break the run."""
        mod = _load_dream("dream_chunk_oldcore")
        chunks = _chunks(mod, 1)

        seen = []

        async def query(*, system, messages, **kwargs):
            if "timeout_s" in kwargs:
                raise TypeError("query() got an unexpected keyword argument 'timeout_s'")
            seen.append(kwargs)
            response = MagicMock()
            response.content = "DRAFT"
            return response

        client = MagicMock()
        client.query = query

        drafts = asyncio.run(_draft(mod, client, chunks, mod._runs_dir() / "run-a"))

        assert drafts == ["DRAFT"]
        assert seen == [{}]

    def test_concurrency_default_and_override(self, dream_env, monkeypatch):
        mod = _load_dream("dream_concurrency")
        assert mod._concurrency() == 4
        monkeypatch.setenv("MULTIPLAI_DREAM_CONCURRENCY", "2")
        assert mod._concurrency() == 2
        monkeypatch.setenv("MULTIPLAI_DREAM_CONCURRENCY", "nonsense")
        assert mod._concurrency() == 4


# ---------------------------------------------------------------------------
# End to end: one run, one proposal, nothing moved
# ---------------------------------------------------------------------------


DRAFT_RESPONSE = """\
# Processed Learnings — 2026-07-30

## Updates for `dev.md`

### 1. A drafted lesson
**Change:** add
> Do the thing.

**Source:** 2026-07-30.md:3

---

## Filtered Out (1 items)

**diary/event-only**
- Shipped it — records what happened (Source: 2026-07-30.md:9)
"""


def _report_client():
    """Drafts return a proposal; the critic returns NOOP (fail-open, no edits)."""
    async def query(*, system, messages, **kwargs):
        response = MagicMock()
        response.content = "NOOP" if system.startswith("You are a strict editor") \
            else DRAFT_RESPONSE
        return response

    client = MagicMock()
    client.query = query
    return client


def _release_lock(mod):
    """Drop the in-process lock so a follow-up run can be simulated."""
    if mod._RUN_LOCK_FD is not None:
        os.close(mod._RUN_LOCK_FD)
        mod._RUN_LOCK_FD = None


class TestReportRunEndToEnd:
    @pytest.fixture
    def seeded(self, dream_env):
        mod = _load_dream("dream_e2e")
        learnings = dream_env["learnings_dir"] / "2026-07-30.md"
        learnings.write_text("\n".join(
            f"## Session Learnings — 2026-07-30T0{i}:00:00+00:00\n"
            f"Session: s{i}\n"
            f"- **[trust: verified]** PATTERN Lesson {i}. → Target: dev.md\n\n---\n"
            for i in range(3)
        ))
        mod.create_client = AsyncMock(return_value=_report_client())
        return mod, learnings

    def test_one_run_writes_one_stamped_proposal(self, seeded, dream_env):
        mod, learnings = seeded
        before = learnings.read_bytes()

        asyncio.run(mod.dream_report())

        written = list(dream_env["dreams_dir"].glob("processed-learnings-*.md"))
        assert len(written) == 1, "a run must leave exactly one pending proposal"
        assert mod._is_unmodified_generated(written[0].read_text())
        assert learnings.read_bytes() == before, "learnings are never moved or rewritten"
        assert learnings.exists()

    def test_blocks_are_ledgered_and_staging_is_cleared(self, seeded):
        mod, _ = seeded
        asyncio.run(mod.dream_report())

        processed = mod.learnings_ledger.load(
            mod.learnings_ledger.default_ledger_path()
        )["processed"]
        assert len(processed) == 3
        assert list(mod._runs_dir().iterdir()) == [], (
            "staged drafts are now inside a written proposal; keeping them would "
            "fold the same content in again next run"
        )

    def test_a_pending_undecided_proposal_is_folded_in(self, seeded, dream_env):
        mod, _ = seeded
        _write_generated(mod, dream_env["dreams_dir"], "processed-learnings-2026-07-29.md")

        asyncio.run(mod.dream_report())

        assert len(list(dream_env["dreams_dir"].glob("processed-learnings-*.md"))) == 1
        assert (dream_env["dreams_dir"] / "superseded" /
                "processed-learnings-2026-07-29.md").exists()
        written = next(dream_env["dreams_dir"].glob("processed-learnings-*.md")).read_text()
        assert "Always fetch before comparing to a remote" in written, (
            "the folded proposal's entries must survive into this run's document"
        )
        assert written.count("## Routing Warnings") == 1, (
            "the folded copy's regenerated sections must not be merged in"
        )
        assert written.count("<!-- dream:generated") == 1

    def test_a_second_run_finds_nothing_new(self, seeded, dream_env, capsys):
        mod, _ = seeded
        asyncio.run(mod.dream_report())
        _release_lock(mod)
        capsys.readouterr()

        asyncio.run(mod.dream_report())

        assert "No new learnings" in capsys.readouterr().out
        assert len(list(dream_env["dreams_dir"].glob("processed-learnings-*.md"))) == 1

    def test_a_hand_edited_proposal_survives_the_next_run(self, seeded, dream_env):
        """Done-means 14: curation is preserved and this run gets a -2 suffix."""
        from datetime import datetime, timezone

        mod, _ = seeded
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        curated_path = _write_generated(
            mod, dream_env["dreams_dir"], f"processed-learnings-{today}.md",
        )
        curated = curated_path.read_text().replace("### 1.", "### 1. (mine)")
        curated_path.write_text(curated)

        asyncio.run(mod.dream_report())

        assert curated_path.read_text() == curated, "hand curation is authoritative"
        names = {p.name for p in dream_env["dreams_dir"].glob("processed-learnings-*.md")}
        assert names == {
            f"processed-learnings-{today}.md",
            f"processed-learnings-{today}-2.md",
        }, "the -2 suffix stays the fallback when a proposal cannot be folded"
        assert not (dream_env["dreams_dir"] / "superseded").exists()


# ---------------------------------------------------------------------------
# Throughput calibration
# ---------------------------------------------------------------------------


class TestThroughputCalibration:
    def test_first_observation_seeds_the_ewma(self, dream_env):
        mod = _load_dream("dream_tp_seed")
        assert mod._calibrated_throughput() is None
        mod._update_throughput(120.0)
        assert mod._calibrated_throughput() == pytest.approx(120.0)

    def test_later_observations_are_smoothed(self, dream_env):
        mod = _load_dream("dream_tp_ewma")
        mod._update_throughput(100.0)
        mod._update_throughput(200.0)
        value = mod._calibrated_throughput()
        assert 100.0 < value < 200.0, "one slow chunk must not swing the next plan"

    def test_outliers_are_clamped(self, dream_env):
        mod = _load_dream("dream_tp_clamp")
        mod._update_throughput(10_000_000.0)
        assert mod._calibrated_throughput() <= mod._THROUGHPUT_MAX

    def test_calibration_does_not_touch_the_gate_state_file(self, dream_env):
        """`dream_state_file()` is what --stamp and the session hooks read."""
        mod = _load_dream("dream_tp_isolation")
        from multiplai_core.paths import get_paths

        mod._update_throughput(120.0)
        assert not get_paths().dream_state_file().exists()


class TestCriticBatching:
    """The critic is input-bound, so a whole proposal cannot go in one call.

    The unbatched pass was handed a 228 KB prompt by a 283 KB fixture run, burned
    both 900 s attempts, and degraded to "keep the merged draft" — meaning the
    second-pass quality gate silently never ran on a large backlog. Batching is
    only safe if two things hold, and both are asserted here: batches reassemble
    to the original byte-for-byte, and a `## ` section is never split (a
    `MERGE <file>#<n> <- <file>#<m>` compares two entries of one file, so
    splitting a file would hide half its duplicates).
    """

    @staticmethod
    def _proposal(sections: list[tuple[str, int]]) -> str:
        out = []
        for name, size in sections:
            out.append(f"## Updates for `{name}`\n\n" + ("x" * size) + "\n\n")
        return "".join(out)

    def test_batches_reassemble_to_the_original(self, dream_env):
        mod = _load_dream("dream_critic_reassemble")
        proposal = self._proposal([(f"f{i}.md", 9_000) for i in range(6)])
        assert "".join(mod._batch_proposal_for_critic(proposal)) == proposal

    def test_no_batch_splits_a_section(self, dream_env):
        mod = _load_dream("dream_critic_nosplit")
        proposal = self._proposal([(f"f{i}.md", 9_000) for i in range(6)])
        for batch in mod._batch_proposal_for_critic(proposal):
            # A batch that split a section would start mid-body, not at a heading.
            assert batch.startswith("## Updates for")

    def test_a_small_proposal_stays_one_call(self, dream_env):
        mod = _load_dream("dream_critic_small")
        proposal = self._proposal([("only.md", 100)])
        assert len(mod._batch_proposal_for_critic(proposal)) == 1

    def test_a_large_proposal_is_split(self, dream_env):
        mod = _load_dream("dream_critic_split")
        proposal = self._proposal([(f"f{i}.md", 9_000) for i in range(10)])
        assert len(mod._batch_proposal_for_critic(proposal)) > 1

    def test_an_oversized_section_gets_its_own_batch_unsplit(self, dream_env):
        """41 KB single sections are real — `claude-code-tools.md` in the fixture."""
        mod = _load_dream("dream_critic_oversized")
        proposal = self._proposal([("small.md", 500), ("huge.md", 60_000)])
        batches = mod._batch_proposal_for_critic(proposal)
        huge = [b for b in batches if "huge.md" in b]
        assert len(huge) == 1
        assert "".join(batches) == proposal

    def test_directives_from_every_batch_are_applied(self, dream_env, monkeypatch):
        """A batched critic must not silently drop later batches' edits."""
        mod = _load_dream("dream_critic_merge")
        proposal = self._proposal([(f"f{i}.md", 9_000) for i in range(6)])
        batches = mod._batch_proposal_for_critic(proposal)
        assert len(batches) > 1, "fixture must actually split for this to mean anything"

        seen = []

        async def fake_query(client, system, messages, timeout_s=None):
            seen.append(messages[0]["content"])
            return MagicMock(content=f"DROP f{len(seen) - 1}.md#1 redundant")

        monkeypatch.setattr(mod, "_query", fake_query)

        from lib import proposal_edits

        captured = {}

        def spy(p, d):
            captured["n"] = len(d)
            return p, [], []

        monkeypatch.setattr(proposal_edits, "apply_directives", spy)
        asyncio.run(mod._critique_proposal(MagicMock(), proposal))
        assert len(seen) == len(batches), "every batch must reach the model"
        assert captured["n"] == len(batches), "every batch's directive must be applied"

    def test_a_failed_batch_loses_only_its_own_directives(self, dream_env, monkeypatch):
        mod = _load_dream("dream_critic_partial")
        proposal = self._proposal([(f"f{i}.md", 9_000) for i in range(6)])
        batches = mod._batch_proposal_for_critic(proposal)
        assert len(batches) > 1

        calls = {"n": 0}

        async def flaky(client, system, messages, timeout_s=None):
            calls["n"] += 1
            if calls["n"] == 1:
                raise TimeoutError("simulated critic batch timeout")
            return MagicMock(content="NOOP")

        monkeypatch.setattr(mod, "_query", flaky)
        # Fails open: the surviving batches still run, and the proposal comes back.
        result = asyncio.run(mod._critique_proposal(MagicMock(), proposal))
        assert calls["n"] == len(batches)
        assert "## Updates for" in result
